version: "3.9"  # optional since v1.27.0
services:
  metrics:
    build: projects/metrics
    ports:
      - "9091:80"
    volumes:
      - "${HOST_WORKSPACE_FOLDER}/projects/metrics/src:/usr/share/nginx/html"
  prometheus:
    build: projects/prometheus
    ports:
      - "9090:9090"
  grafana:
    build: projects/grafana
    ports:
      - "9092:3000"