#! /bin/bash

action=$1

source "${CONTAINER_WORKSPACE_FOLDER}/auto/_utils.sh"

printHelp() {
    echo "solution start"
    echo "- Build your projects, spin up all containers using docker compose, then publish any assets as necessary."
    echo ""
    echo "solution stop"
    echo "- Stop all containers running in your docker composition."
    echo ""
    echo "solution help"
    echo "- Print this help message."
}

case $action in
    start)
        projects=`get-projects`
        for project in $projects
        do
            build-project $project
        done

        pushd $CONTAINER_WORKSPACE_FOLDER
        docker-compose build
        docker-compose up -d
        popd > /dev/null

        while [[ `curl -s http://host.docker.internal:9092/api/health | jq '.database' --raw-output` != 'ok' ]]
        do
            echo "Waiting for grafana to start up..."
            sleep 1
        done
        echo "Grafana has started."

        for project in $projects
        do
            release-project $project
        done
        ;;
    stop)
        pushd $CONTAINER_WORKSPACE_FOLDER
        docker-compose down
        popd > /dev/null
        ;;
    *)
        printHelp
        ;;
esac