{
 "title": "Platform Pilot Status",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(dnanexus_pilot_last_deploy_successful, instance)"
    }
   },
   {
    "name": "Stack",
    "query": {
     "query": "label_values(dnanexus_headwaters_service_status_target,stack)"
    }
   },
   {
    "name": "Service",
    "query": {
     "query": "label_values(dnanexus_headwaters_service_status_target,name)"
    }
   },
   {
    "name": "Image",
    "query": {
     "query": "label_values(container_start_time_seconds, image)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pilot Deploy Success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(dnanexus_pilot_last_deploy_successful{service=~\"${Stack:pipe}\"})"
    }
   ]
  },
  {
   "title": "Docker Stack Deploy Success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(dnanexus_headwaters_docker_stack_deploy_success{service=~\"${Stack:pipe}\"})"
    }
   ]
  },
  {
   "title": "Docker Service Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dnanexus_headwaters_service_status_current{stack=~\"${Stack:pipe}\"}) / sum(dnanexus_headwaters_service_status_target{stack=~\"${Stack:pipe}\"})"
    }
   ]
  },
  {
   "title": "Platform Pilot Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "dnanexus_pilot_last_deploy_successful{instance=~\"${Node:pipe}\", service=~\"${Stack:pipe}\"}"
    },
    {
     "expr": "time() - dnanexus_pilot_last_deploy_time_seconds{instance=~\"${Node:pipe}\", service=~\"${Stack:pipe}\"}"
    }
   ]
  },
  {
   "title": "Docker Stack Deploy Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 4 },
   "targets": [
    {
     "expr": "dnanexus_headwaters_docker_stack_deploy_success{instance=~\"${Node:pipe}\", service=~\"${Stack:pipe}\"}"
    },
    {
     "expr": "time() - node_textfile_mtime_seconds{file=\"headwaters-stack-status.prom\",instance=~\"${Node:pipe}\", service=~\"${Stack:pipe}\"}"
    }
   ]
  },
  {
   "title": "Current Docker Images - $Stack",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "time() - label_replace(label_replace(label_replace(label_replace(container_start_time_seconds{container_label_com_docker_stack_namespace=~\"$Stack\", instance=~\"${Node:pipe}\"}, \"z_repo\", \"$1\", \"image\", \"(.*)/.*\"), \"b_imagename\", \"$1\", \"image\", \".*/(.*):.*@.*\"), \"c_imageversion\", \"$1\", \"image\", \".*/.*:(.*)@.*\"),\"a_servicename\", \"$1\", \"container_label_com_docker_swarm_service_name\", \".*?_(.*)\")"
    }
   ]
  },
  {
   "title": "Docker Service Health",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "dnanexus_headwaters_service_status_current / dnanexus_headwaters_service_status_target{instance=~\"${Node:pipe}\", stack=~\"$Stack\"}"
    },
    {
     "expr": "dnanexus_service_info{delivery=\"containerized\",instance=~\"${Node:pipe}\", service=~\"${Stack:pipe}\"}"
    },
    {
     "expr": "time() - node_textfile_mtime_seconds{file=\"headwaters-services.prom\",instance=~\"${Node:pipe}\", service=~\"$Stack\"}"
    }
   ]
  },
  {
   "title": "Service Availability",
   "type": "state-timeline",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "dnanexus_headwaters_service_status_current / dnanexus_headwaters_service_status_target{instance=~\"${Node:pipe}\", stack=\"${Stack:pipe}\"}",
     "legendFormat": "{{name}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "state-timeline",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(label_replace(label_replace(label_replace(label_replace(container_start_time_seconds{container_label_com_docker_stack_namespace=~\".+\", instance=~\"grafana02.in.vdev\"}, \"z_repo\", \"$1\", \"image\", \"(.*)/.*\"), \"b_imagename\", \"$1\", \"image\", \".*/(.*):.*@.*\"), \"c_imageversion\", \"$1\", \"image\", \".*/.*:(.*)@.*\"),\"a_servicename\", \"$1\", \"container_label_com_docker_swarm_service_name\", \".*_(.*)\")) by (instance, b_imagename, c_imageversion)",
       "legendFormat": "{{b_imagename}}:{{c_imageversion}}"
      }
     ]
    }
   ]
  }
 ]
}