{
 "title": "Compute Dashboard",
 "tags": [
  "sync",
  "team-compute"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,10m,20m,30m,1h,2h,3h,6h" },
   {
    "name": "region",
    "query": "label_values(instances_total, region)"
   }
  ]
 },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# Workers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(instances_total)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "awsInstance",
     "query": "SELECT sum(\"numActive\") from longterm.workers_by_region where time > now() - 10m ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# Running Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "activeJobs",
     "query": "SELECT sum(\"numRunning\") from longterm.running_jobs_by_region where time > now() - 10m",
     "select": [
      [
       { "params": [ "jobId" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "running" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Active Instances by State",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "expr": "sum(instances_total) by(state) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "measurement": "workers_by_state",
     "query": "SELECT max(\"numActive\") FROM \"longterm\".\"workers_by_state\" WHERE $timeFilter GROUP BY time($__interval), \"state\" fill(0)",
     "select": [
      [
       { "params": [ "numActive" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Instances by Instance Type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "expr": "sum(instances_total) by(instance_type)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "{{instance_type}}",
     "measurement": "workers_by_state",
     "query": "SELECT max(\"numActive\") FROM \"longterm\".\"workers_by_state\" WHERE $timeFilter GROUP BY time($__interval), \"state\" fill(0)",
     "select": [
      [
       { "params": [ "numActive" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Active Instances by Region",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "expr": "sum(instances_total) by(region)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "{{region}}",
     "measurement": "workers_by_state",
     "query": "SELECT max(\"numActive\") FROM \"longterm\".\"workers_by_state\" WHERE $timeFilter GROUP BY time($__interval), \"state\" fill(0)",
     "select": [
      [
       { "params": [ "numActive" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Instances by Spot Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_isSpot",
     "expr": "sum(instances_total{spot=~\"true|false\"}) by (spot)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "isSpot" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "{{spot}}",
     "measurement": "workers_by_spot",
     "query": "SELECT count(DISTINCT(\"instanceId\")) FROM \"worker\" WHERE $timeFilter GROUP BY time($__interval), \"state\" fill(0)",
     "select": [
      [
       { "params": [ "numActive" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "isSpot", "operator": "=", "value": "true" },
      { "condition": "OR", "key": "isSpot", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Running Jobs By Region",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "region" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "running_jobs_by_region",
     "query": "SELECT count(DISTINCT(\"instanceId\")) FROM \"worker\" WHERE $timeFilter GROUP BY time($__interval), \"state\" fill(0)",
     "select": [
      [
       { "params": [ "numRunning" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Runnable Jobs By Region",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "region" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "runnable_jobs_by_region",
     "query": "SELECT count(DISTINCT(\"instanceId\")) FROM \"worker\" WHERE $timeFilter GROUP BY time($__interval), \"state\" fill(0)",
     "select": [
      [
       { "params": [ "numRunning" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Unresponsive Worker Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Unresponsive Instances by Region",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_region",
     "expr": "sum(instances_total{state=\"nonResponsive\"}) by (region)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "region" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "{{region}}",
     "measurement": "workers_by_region",
     "query": "SELECT sum(instances_tota FROM \"longterm\".\"unresponsive_workers_by_region\" WHERE $timeFilter GROUP BY time($__interval), \"region\" fill(0)",
     "select": [
      [
       { "params": [ "numActive" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unresponsive Instances by Instance Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instanceType",
     "expr": "sum(instances_total{state=\"nonResponsive\"}) by (instance_type)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "region" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "{{instance_type}}",
     "measurement": "workers_by_region",
     "query": "SELECT max(\"numUnresponsive\") FROM \"longterm\".\"unresponsive_workers_by_instanceType\" WHERE $timeFilter GROUP BY time($__interval), \"instanceType\" fill(0)",
     "select": [
      [
       { "params": [ "numActive" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Worker Efficiency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "20min Avg By Region",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT moving_average(MAX(percEff), 10) FROM \"longterm\".\"worker_eff_by_region\" WHERE $timeFilter GROUP BY time($__interval), region fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Worker Efficiency by Region",
   "type": "graph",
   "description": "Num busy / Total = % of workers in use",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_region",
     "expr": "sum(avg_over_time(instances_total{state=\"busy\"}[$interval])) by (region) / sum(avg_over_time(instances_total[$interval])) by (region)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{region}}",
     "query": "SELECT moving_average(MAX(percEff), 10) FROM \"longterm\".\"worker_eff_by_region\" WHERE $timeFilter GROUP BY time($__interval), region fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {}
   ]
  },
  {
   "title": "Worker Efficiency: $region",
   "type": "graph",
   "description": "Num busy / Total = % of workers in use",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 44 },
   "repeat": "region",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_region",
     "expr": "sum(avg_over_time(instances_total{state=\"busy\", region=\"$region\"}[$interval])) by (region) / sum(avg_over_time(instances_total{region=\"$region\"}[$interval])) by (region)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{region}}",
     "query": "SELECT moving_average(MAX(percEff), 10) FROM \"longterm\".\"worker_eff_by_region\" WHERE $timeFilter GROUP BY time($__interval), region fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {}
   ]
  },
  {
   "title": "AWS US-East 30 day",
   "type": "singlestat",
   "description": "AWS:US-East-1 30 day average worker efficiency",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 44 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(percEff)*100 FROM \"longterm\".\"worker_eff_by_region\" WHERE time > now() - 30d AND \"region\"='us-east-1' fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Azure WestUS 30 day",
   "type": "singlestat",
   "description": "Azure:WestUS 30 day average worker efficiency",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 44 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(percEff)*100 FROM \"longterm\".\"worker_eff_by_region\" WHERE time > now() - 30d AND \"region\"='westus' fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "US-East Spot Conditions As % of bidPrice",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_instanceType",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instanceId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Instance",
     "query": "SELECT LAST(\"marketPriceLow\")/MAX(\"bidPrice\") AS spotCond FROM \"spotConditions\" WHERE \"region\" = 'us-east-1' AND $timeFilter GROUP BY time($__interval), instanceType fill(none)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "US-East-1 Worker startup",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"startupTime\"/(1000*60) FROM \"workerStartup\" WHERE \"region\"='us-east-1' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Azure Westus Worker startup",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"startupTime\"/(1000*60) FROM \"workerStartup\" WHERE \"region\"='westus' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Non-Spot Job Assignable Duration",
   "type": "graph",
   "description": "The length of time a job waits after becoming \nassignable to getting a worker",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_region",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "jobLogs",
     "query": "SELECT \"duration\" FROM \"assignableDuration\" WHERE $timeFilter AND \"instanceType\" !~ /_s_/ AND \"isWRD\" = 'false' GROUP BY region",
     "select": [
      [
       { "params": [ "numLines" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "[[tag_region]]_WRD",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "jobLogs",
     "query": "SELECT \"duration\" FROM \"assignableDuration\" WHERE $timeFilter AND \"instanceType\" !~ /_s_/ AND \"isWRD\" = 'true' GROUP BY region",
     "select": [
      [
       { "params": [ "numLines" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Spot Job Assignable Duration",
   "type": "graph",
   "description": "The length of time a job waits after becoming \nassignable to getting a worker",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_region",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "jobLogs",
     "query": "SELECT \"duration\" FROM \"assignableDuration\" WHERE $timeFilter AND \"instanceType\" =~ /_s_/ AND \"isWRD\" = 'false' GROUP BY region",
     "select": [
      [
       { "params": [ "numLines" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "[[tag_region]]_WRD",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "jobLogs",
     "query": "SELECT \"duration\" FROM \"assignableDuration\" WHERE $timeFilter AND \"instanceType\" =~ /_s_/ AND \"isWRD\" = 'true' GROUP BY region",
     "select": [
      [
       { "params": [ "numLines" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}