{
 "title": "API Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h2>Global Metrics</h2></center>"
  },
  {
   "title": "Requests/min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_latency_milliseconds_histogram_count[1m]))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Errors/min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_latency_milliseconds_histogram_count{status=~\"5..\"}[1m]))",
     "legendFormat": "Total Errors"
    }
   ]
  },
  {
   "title": "Req Duration - p90, 5 min avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(api_latency_milliseconds_histogram_bucket[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(api_latency_milliseconds_histogram_bucket[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(api_latency_milliseconds_histogram_bucket[5m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "content": "<center><h2>By Path</h2></center>"
  },
  {
   "title": "Requests/min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_latency_milliseconds_histogram_count[1m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Errors/min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_latency_milliseconds_histogram_count{status=~\"5..\"}[1m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Req Duration - p90, 5 min avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(api_latency_milliseconds_histogram_bucket[5m])) by (le, path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 22 },
   "content": "<center><h2>By Status Code</h2></center>"
  },
  {
   "title": "Requests/min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_latency_milliseconds_histogram_count[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Errors/min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_latency_milliseconds_histogram_count{status=~\"5..\"}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Req Duration - p90, 5 min avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(api_latency_milliseconds_histogram_bucket[5m])) by (le, status))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 33 },
   "content": "<center><h2>By Instance</h2></center>"
  },
  {
   "title": "Requests/min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_latency_milliseconds_histogram_count[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Errors/min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_latency_milliseconds_histogram_count{status=~\"5..\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Req Duration - p90, 5 min avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(api_latency_milliseconds_histogram_bucket[5m])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 44 },
   "content": "<center><h2>Distribution by Status Code</h2></center>"
  },
  {
   "title": "% of Requests by Instance (1 hr moving average)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_latency_milliseconds_histogram_count[1h])) by(status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "% of Requests by Status (10 min moving average)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_latency_milliseconds_histogram_count[10m])) by(status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 54 },
   "content": "<center><h2>Distribution by Instance</h2></center>"
  },
  {
   "title": "% of Requests by Instance (1 hr moving average)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_latency_milliseconds_histogram_count[1h])) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "% of Requests by Instance (10 min moving average)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_latency_milliseconds_histogram_count[10m])) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 64 },
   "content": "<center><h2>Saturation</h2></center>"
  },
  {
   "title": "Load Average (5min)",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load5{instance=~\"api.*\"} ",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}