{
 "title": "Lobby 3",
 "tags": [
  "sync",
  "lobby",
  "team-compute"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<p style=\"text-align: center;font-size:50px\">Jobs: Past 24 Hours</p>"
  },
  {
   "title": "Running Jobs By Region",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "region" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "running_jobs_by_region",
     "query": "SELECT count(DISTINCT(\"instanceId\")) FROM \"worker\" WHERE $timeFilter GROUP BY time($__interval), \"state\" fill(0)",
     "select": [
      [
       { "params": [ "numRunning" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Runnable Jobs By Region",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "region" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "runnable_jobs_by_region",
     "query": "SELECT count(DISTINCT(\"instanceId\")) FROM \"worker\" WHERE $timeFilter GROUP BY time($__interval), \"state\" fill(0)",
     "select": [
      [
       { "params": [ "numRunning" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job Runtime US-East-1",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "alias": "$tag__region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  \"timeDelta\" FROM \"jobStateTransitions\" WHERE ((\"from\" = 'running' AND \"to\" = 'done') OR (\"from\" = 'running' AND \"to\" = 'waiting_on_output')) AND \"region\"='aws:us-east-1' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job Runtime CN-North-1",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "targets": [
    {
     "alias": "$tag__region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  \"timeDelta\" FROM \"jobStateTransitions\" WHERE ((\"from\" = 'running' AND \"to\" = 'done') OR (\"from\" = 'running' AND \"to\" = 'waiting_on_output')) AND \"region\"='aws:cn-north-1' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job Runtime AP-SouthEast-2",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 13 },
   "targets": [
    {
     "alias": "$tag__region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  \"timeDelta\" FROM \"jobStateTransitions\" WHERE ((\"from\" = 'running' AND \"to\" = 'done') OR (\"from\" = 'running' AND \"to\" = 'waiting_on_output')) AND \"region\"='aws:ap-southeast-2' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job Runtime EU-Central-1",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 13 },
   "targets": [
    {
     "alias": "$tag__region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  \"timeDelta\" FROM \"jobStateTransitions\" WHERE ((\"from\" = 'running' AND \"to\" = 'done') OR (\"from\" = 'running' AND \"to\" = 'waiting_on_output')) AND \"region\"='aws:eu-central-1' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job Runtime Azure WestUS",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 13 },
   "targets": [
    {
     "alias": "$tag__region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  \"timeDelta\" FROM \"jobStateTransitions\" WHERE ((\"from\" = 'running' AND \"to\" = 'done') OR (\"from\" = 'running' AND \"to\" = 'waiting_on_output')) AND \"region\"='azure:westus' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Completed Jobs Per Region",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "region" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "completed_jobs_by_region",
     "select": [
      [
       { "params": [ "numCompleted" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Jobs Per Region",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "region" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "failed_jobs_by_region",
     "query": "SELECT count(DISTINCT(\"jobId\")) FROM \"jobStateTransitions\" WHERE \"to\" = 'failed' AND $timeFilter GROUP BY time($__interval), \"region\" fill(0)",
     "select": [
      [
       { "params": [ "numFailed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Terminated Jobs Per Region",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "region" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "terminated_jobs_by_region",
     "query": "SELECT count(DISTINCT(\"jobId\")) FROM \"jobStateTransitions\" WHERE \"to\" = 'terminated' AND $timeFilter GROUP BY time($__interval), \"region\" fill(0)",
     "select": [
      [
       { "params": [ "numTerminated" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}