{
 "title": "Data Dashboard",
 "tags": [ "data-team" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "US-East-1 Data Size",
   "type": "singlestat",
   "description": "Current size of data in our US-East 1 bucket",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "limit": "1",
     "measurement": "totalData",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws:us-east-1" }
     ]
    }
   ]
  },
  {
   "title": "Frankfurt Data Size",
   "type": "singlestat",
   "description": "Current size of data in our EU-Central-1 bucket",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "limit": "1",
     "measurement": "totalData",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws:eu-central-1" }
     ]
    }
   ]
  },
  {
   "title": "China Data Size",
   "type": "singlestat",
   "description": "Current size of data in our CN-North-1 bucket",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "limit": "1",
     "measurement": "totalData",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws:cn-north-1" }
     ]
    }
   ]
  },
  {
   "title": "Sydney Data Size",
   "type": "singlestat",
   "description": "Current size of data in our Sydney bucket",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "limit": "1",
     "measurement": "totalData",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "aws:ap-southeast-2" }
     ]
    }
   ]
  },
  {
   "title": "Azure Data Size",
   "type": "singlestat",
   "description": "Current size of data in our Azure Blob Container",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "limit": "1",
     "measurement": "totalData",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "azure:westus" }
     ]
    }
   ]
  },
  {
   "title": "S3 Deletions Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "s3deletions",
     "select": [
      [
       { "params": [ "queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Azure Deletions Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Unprocessed Queue Size",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "azureDeletions",
     "select": [
      [
       { "params": [ "azure-deletion-queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Expired Auth Tokens",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "auth_tokens",
     "select": [
      [
       { "params": [ "expired" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Project Deletion Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "deletions",
     "select": [
      [
       { "params": [ "deferred-deletion-queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sponsorship Cleanup Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "data",
     "select": [
      [
       { "params": [ "sponsorship-queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}