{
 "title": "SecOps",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "version",
    "query": "label_values(auditd_rules, version)"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# hosts on version $version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "repeat": "version",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(auditd_rules{version=\"$version\"})"
    }
   ]
  },
  {
   "title": "# hosts on version $version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(auditd_rules{version=\"$version\"})"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "hosts on version $version",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "repeat": "version",
   "targets": [
    {
     "expr": "auditd_rules{version=\"$version\"}"
    }
   ]
  },
  {
   "title": "hosts on version $version",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "auditd_rules{version=\"$version\"}"
    }
   ]
  },
  {
   "title": "auditd versions over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(auditd_rules) by (version)", "legendFormat": "{{version}}" }
   ]
  }
 ]
}