{
 "title": "Event Dispatcher Lambda",
 "description": "Metrics for the event dispatcher lambda function",
 "tags": [
  "data-team",
  "audit-log"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Number of Invocations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "aws_lambda_invocations_sum{function_name=\"eventdispatcher-vprod-EventDispatcher-1RAJBQJ89U9M7\"}",
     "legendFormat": "Invocation Count"
    }
   ]
  },
  {
   "title": "Number of Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "aws_lambda_errors_sum{function_name=\"eventdispatcher-vprod-EventDispatcher-1RAJBQJ89U9M7\"}",
     "legendFormat": "Error Count"
    }
   ]
  },
  {
   "title": "Average Lag Reading from dx-event-stream-vprod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms", "label": "Iterator Lag" }
   ],
   "targets": [
    {
     "expr": "aws_lambda_iterator_age_average{function_name=\"eventdispatcher-vprod-EventDispatcher-1RAJBQJ89U9M7\"}",
     "legendFormat": "Average Iterator Age"
    },
    { "legendFormat": "Max Iterator Age" }
   ]
  },
  {
   "title": "Execution Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms", "label": "Execution Time" }
   ],
   "targets": [
    {
     "expr": "aws_lambda_duration_average{function_name=\"eventdispatcher-vprod-EventDispatcher-1RAJBQJ89U9M7\"}",
     "legendFormat": "Average Execution Time (ms)"
    },
    {}
   ]
  },
  {
   "title": "Throttled Events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "aws_lambda_throttles_sum{function_name=\"eventdispatcher-vprod-EventDispatcher-1RAJBQJ89U9M7\"}",
     "legendFormat": "Number of Throttled Events"
    }
   ]
  }
 ]
}