{
 "title": "TIP Container Versions",
 "tags": [ "tip" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h2>TIP Container Versions Running Right Now</h2></center>"
  },
  {
   "title": "Count by Tag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(label_replace(label_replace(container_last_seen{image!~\"google/cadvisor.*|telegraf.*\", image=~\".+\", sre_role=~\"TIP.*\"}, \"tag\", \"$1\", \"image\", \".*:(.*)\"), \"imagename\", \"$1\", \"image\", \".*/(.*):.*\")) by (tag)",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "Count by Tag & Image Name",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(label_replace(label_replace(container_last_seen{image!~\"google/cadvisor.*|telegraf.*\", image=~\".+\", sre_role=~\"TIP.*\"}, \"tag\", \"$1\", \"image\", \".*:(.*)\"), \"imagename\", \"$1\", \"image\", \".*/(.*):.*\")) by (tag, imagename)",
     "legendFormat": "{{tag}} ({{imagename}})"
    }
   ]
  },
  {
   "title": "Container Details",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "label_replace(label_replace(container_last_seen{image!~\"google/cadvisor.*|telegraf.*\", image=~\".+\", sre_role=~\"TIP.*\"}, \"tag\", \"$1\", \"image\", \".*:(.*)\"), \"imagename\", \"$1\", \"image\", \".*/(.*):.*\")"
    }
   ]
  }
 ]
}