{
 "title": "Audit Log Processor - DynamoDB",
 "description": "Kinesis Client Library DynamoDB table for the Audit Log Processor component",
 "tags": [
  "audit-log",
  "data-team"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Write Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Write Capacity Units" }
   ],
   "targets": [
    {
     "expr": "aws_dynamodb_consumed_write_capacity_units_sum{table_name=\"dx-auditlog-processor-vprod\"}",
     "legendFormat": "Consumed Write Capacity Units"
    },
    {
     "expr": "aws_dynamodb_provisioned_write_capacity_units_sum{table_name=\"dx-auditlog-processor-vprod\"}",
     "legendFormat": "Provisioned Write Capacity Units"
    },
    {}
   ]
  },
  {
   "title": "Read Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Read Capacity Units" }
   ],
   "targets": [
    {
     "expr": "aws_dynamodb_consumed_read_capacity_units_sum{table_name=\"dx-auditlog-processor-vprod\"}",
     "legendFormat": "Consumed Read Capacity"
    },
    {
     "expr": "aws_dynamodb_provisioned_read_capacity_units_sum{table_name=\"dx-auditlog-processor-vprod\"}",
     "legendFormat": "Provisioned Read Capacity"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Average Latency (ms)" }
   ],
   "targets": [
    {
     "expr": "avg(aws_dynamodb_successful_request_latency_average{operation=~\"BatchWriteItem|PutItem|DeleteItem|UpdateItem\",table_name=\"dx-auditlog-processor-vprod\"})",
     "legendFormat": "Average Write Latency (ms)"
    },
    {
     "expr": "avg(aws_dynamodb_successful_request_latency_average{operation=~\"Query|GetItem|BatchGetItem|Scan\", table_name=\"dx-auditlog-processor-vprod\"})",
     "legendFormat": "Average Read Latency (ms)"
    }
   ]
  },
  {
   "title": "Throttled Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Throttled Requests" }
   ],
   "targets": [
    {
     "expr": "aws_dynamodb_throttled_requests_sum{table_name=\"dx-auditlog-processor-vprod\"}",
     "legendFormat": "Throttled Requests"
    }
   ]
  }
 ]
}