{
 "title": "TIP Service Probes",
 "tags": [
  "blackbox",
  "tip"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Cluster",
    "query": "label_values(probe_success{sre_role=~\"TIP.*\"}, sre_role)"
   },
   {
    "name": "target",
    "label": "Instance",
    "query": "label_values(probe_success{instance=~\".*(thrift|metastore|hdfs|looker|yarn).*$env.*\"}, instance)"
   },
   {
    "name": "looker",
    "query": "label_values(node_boot_time{instance=~\".*looker.*\", instance=~\".*$env.*\"}, instance)"
   },
   { "name": "env", "query": "dx1,dx2" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h2>Service Health By Cluster</h2></center>"
  },
  {
   "title": "$service",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "repeat": "service",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(probe_success{sre_role=\"TIP-$service\",job=~\".*_probe\", instance=~\".*$env.*\"} == 1) / count(probe_success{sre_role=\"TIP-$service\",job=~\".*_probe\", instance=~\".*$env.*\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "$service",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(probe_success{sre_role=\"TIP-$service\",job=~\".*_probe\", instance=~\".*$env.*\"} == 1) / count(probe_success{sre_role=\"TIP-$service\",job=~\".*_probe\", instance=~\".*$env.*\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "$service",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(probe_success{sre_role=\"TIP-$service\",job=~\".*_probe\", instance=~\".*$env.*\"} == 1) / count(probe_success{sre_role=\"TIP-$service\",job=~\".*_probe\", instance=~\".*$env.*\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "VIZSYNC",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(up{job=\"vizsync\"})"
    }
   ]
  },
  {
   "title": "$service",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(probe_success{sre_role=\"TIP-$service\",job=~\".*_probe\", instance=~\".*$env.*\"} == 1) / count(probe_success{sre_role=\"TIP-$service\",job=~\".*_probe\", instance=~\".*$env.*\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "$service",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(probe_success{sre_role=\"TIP-$service\",job=~\".*_probe\", instance=~\".*$env.*\"} == 1) / count(probe_success{sre_role=\"TIP-$service\",job=~\".*_probe\", instance=~\".*$env.*\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "$service",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(probe_success{sre_role=\"TIP-$service\",job=~\".*_probe\", instance=~\".*$env.*\"} == 1) / count(probe_success{sre_role=\"TIP-$service\",job=~\".*_probe\", instance=~\".*$env.*\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "$service",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(probe_success{sre_role=\"TIP-$service\",job=~\".*_probe\", instance=~\".*$env.*\"} == 1) / count(probe_success{sre_role=\"TIP-$service\",job=~\".*_probe\", instance=~\".*$env.*\"}) or vector(0)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 5 },
   "content": "<center><h2>Service Health By Instance</h2></center>"
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "target" },
  {
   "title": "Current Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$target\",job=~\".*_probe\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=~\"$target\",job=~\".*_probe\"}[$__range])"
    }
   ]
  },
  {
   "title": "Service",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(probe_success{job=~\".*_probe\", instance=~\"$target\"}, \"type\", \"$1\", \"sre_role\", \"TIP-(.*)\")",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Probe",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 8 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(probe_success{job=~\".*_probe\", instance=~\"$target\"}, \"type\", \"$1\", \"job\", \"(.*)_.*\")",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Avg Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 8 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{instance=~\"$target\",job=~\".*_probe\"}[$__range])"
    }
   ]
  },
  {
   "title": "Probe Duration (5 min moving avg)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{instance=~\"$target\",job=~\".*_probe\"}[5m])",
     "legendFormat": "seconds (5 min avg)"
    }
   ]
  },
  {
   "title": "Probe Success Over Time",
   "type": "graph",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(probe_success{instance=~\"$target\",job=~\".*_probe\"}==1)",
     "legendFormat": "Success"
    },
    {
     "expr": "count(probe_success{instance=~\"$target\",job=~\".*_probe\"}==0)",
     "legendFormat": "Failure"
    }
   ]
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Current Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$target\",job=~\".*_probe\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=~\"$target\",job=~\".*_probe\"}[$__range])"
    }
   ]
  },
  {
   "title": "Service",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(probe_success{job=~\".*_probe\", instance=~\"$target\"}, \"type\", \"$1\", \"sre_role\", \"TIP-(.*)\")",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Probe",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 12 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(probe_success{job=~\".*_probe\", instance=~\"$target\"}, \"type\", \"$1\", \"job\", \"(.*)_.*\")",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Avg Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 12 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{instance=~\"$target\",job=~\".*_probe\"}[$__range])"
    }
   ]
  },
  {
   "title": "Probe Duration (5 min moving avg)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 13, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{instance=~\"$target\",job=~\".*_probe\"}[5m])",
     "legendFormat": "seconds (5 min avg)"
    }
   ]
  },
  {
   "title": "Probe Success Over Time",
   "type": "graph",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(probe_success{instance=~\"$target\",job=~\".*_probe\"}==1)",
     "legendFormat": "Success"
    },
    {
     "expr": "count(probe_success{instance=~\"$target\",job=~\".*_probe\"}==0)",
     "legendFormat": "Failure"
    }
   ]
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Current Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$target\",job=~\".*_probe\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 16 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=~\"$target\",job=~\".*_probe\"}[$__range])"
    }
   ]
  },
  {
   "title": "Service",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 16 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(probe_success{job=~\".*_probe\", instance=~\"$target\"}, \"type\", \"$1\", \"sre_role\", \"TIP-(.*)\")",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Probe",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 16 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(probe_success{job=~\".*_probe\", instance=~\"$target\"}, \"type\", \"$1\", \"job\", \"(.*)_.*\")",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Avg Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 16 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{instance=~\"$target\",job=~\".*_probe\"}[$__range])"
    }
   ]
  },
  {
   "title": "Probe Duration (5 min moving avg)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 13, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{instance=~\"$target\",job=~\".*_probe\"}[5m])",
     "legendFormat": "seconds (5 min avg)"
    }
   ]
  },
  {
   "title": "Probe Success Over Time",
   "type": "graph",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(probe_success{instance=~\"$target\",job=~\".*_probe\"}==1)",
     "legendFormat": "Success"
    },
    {
     "expr": "count(probe_success{instance=~\"$target\",job=~\".*_probe\"}==0)",
     "legendFormat": "Failure"
    }
   ]
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Current Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$target\",job=~\".*_probe\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 20 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=~\"$target\",job=~\".*_probe\"}[$__range])"
    }
   ]
  },
  {
   "title": "Service",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 20 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(probe_success{job=~\".*_probe\", instance=~\"$target\"}, \"type\", \"$1\", \"sre_role\", \"TIP-(.*)\")",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Probe",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 20 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(probe_success{job=~\".*_probe\", instance=~\"$target\"}, \"type\", \"$1\", \"job\", \"(.*)_.*\")",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Avg Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 20 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{instance=~\"$target\",job=~\".*_probe\"}[$__range])"
    }
   ]
  },
  {
   "title": "Probe Duration (5 min moving avg)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 13, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{instance=~\"$target\",job=~\".*_probe\"}[5m])",
     "legendFormat": "seconds (5 min avg)"
    }
   ]
  },
  {
   "title": "Probe Success Over Time",
   "type": "graph",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(probe_success{instance=~\"$target\",job=~\".*_probe\"}==1)",
     "legendFormat": "Success"
    },
    {
     "expr": "count(probe_success{instance=~\"$target\",job=~\".*_probe\"}==0)",
     "legendFormat": "Failure"
    }
   ]
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Current Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$target\",job=~\".*_probe\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 24 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=~\"$target\",job=~\".*_probe\"}[$__range])"
    }
   ]
  },
  {
   "title": "Service",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 24 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(probe_success{job=~\".*_probe\", instance=~\"$target\"}, \"type\", \"$1\", \"sre_role\", \"TIP-(.*)\")",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Probe",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 24 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(probe_success{job=~\".*_probe\", instance=~\"$target\"}, \"type\", \"$1\", \"job\", \"(.*)_.*\")",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Avg Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 24 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{instance=~\"$target\",job=~\".*_probe\"}[$__range])"
    }
   ]
  },
  {
   "title": "Probe Duration (5 min moving avg)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 13, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{instance=~\"$target\",job=~\".*_probe\"}[5m])",
     "legendFormat": "seconds (5 min avg)"
    }
   ]
  },
  {
   "title": "Probe Success Over Time",
   "type": "graph",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(probe_success{instance=~\"$target\",job=~\".*_probe\"}==1)",
     "legendFormat": "Success"
    },
    {
     "expr": "count(probe_success{instance=~\"$target\",job=~\".*_probe\"}==0)",
     "legendFormat": "Failure"
    }
   ]
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Current Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$target\",job=~\".*_probe\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 28 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=~\"$target\",job=~\".*_probe\"}[$__range])"
    }
   ]
  },
  {
   "title": "Service",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 28 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(probe_success{job=~\".*_probe\", instance=~\"$target\"}, \"type\", \"$1\", \"sre_role\", \"TIP-(.*)\")",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Probe",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 28 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(probe_success{job=~\".*_probe\", instance=~\"$target\"}, \"type\", \"$1\", \"job\", \"(.*)_.*\")",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Avg Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 28 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{instance=~\"$target\",job=~\".*_probe\"}[$__range])"
    }
   ]
  },
  {
   "title": "Probe Duration (5 min moving avg)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 13, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{instance=~\"$target\",job=~\".*_probe\"}[5m])",
     "legendFormat": "seconds (5 min avg)"
    }
   ]
  },
  {
   "title": "Probe Success Over Time",
   "type": "graph",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(probe_success{instance=~\"$target\",job=~\".*_probe\"}==1)",
     "legendFormat": "Success"
    },
    {
     "expr": "count(probe_success{instance=~\"$target\",job=~\".*_probe\"}==0)",
     "legendFormat": "Failure"
    }
   ]
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Current Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$target\",job=~\".*_probe\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 32 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=~\"$target\",job=~\".*_probe\"}[$__range])"
    }
   ]
  },
  {
   "title": "Service",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 32 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(probe_success{job=~\".*_probe\", instance=~\"$target\"}, \"type\", \"$1\", \"sre_role\", \"TIP-(.*)\")",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Probe",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 32 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(probe_success{job=~\".*_probe\", instance=~\"$target\"}, \"type\", \"$1\", \"job\", \"(.*)_.*\")",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Avg Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 32 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{instance=~\"$target\",job=~\".*_probe\"}[$__range])"
    }
   ]
  },
  {
   "title": "Probe Duration (5 min moving avg)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 13, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{instance=~\"$target\",job=~\".*_probe\"}[5m])",
     "legendFormat": "seconds (5 min avg)"
    }
   ]
  },
  {
   "title": "Probe Success Over Time",
   "type": "graph",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(probe_success{instance=~\"$target\",job=~\".*_probe\"}==1)",
     "legendFormat": "Success"
    },
    {
     "expr": "count(probe_success{instance=~\"$target\",job=~\".*_probe\"}==0)",
     "legendFormat": "Failure"
    }
   ]
  }
 ]
}