{
 "title": "Headwaters Deployments",
 "tags": [ "devops" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Service",
    "query": {
     "query": "label_values(dnanexus_service_info{delivery=\"containerized\",sre_role!~\"TIP.*\",  service!~\"mongos|mempstree\"},service)"
    }
   },
   {
    "name": "Image",
    "query": {
     "query": "label_values(container_start_time_seconds, image)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Headwaters Versions",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "dnanexus_service_info{delivery=\"containerized\", sre_role!~\"TIP.*\", service!~\"mempstree|mongos|upstart_nginx\", service=~\"${Service:pipe}\"}"
    }
   ]
  },
  { "title": "Headwaters Repo Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Headwaters Versions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(dnanexus_service_info{service=~\"${Service:pipe}\", delivery=\"containerized\", sre_role!~\"TIP.*\", repo=~\"headwaters\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Image Versions per Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
     "repeat": "Image",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Headwaters Versions per Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Service",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
     "repeat": "Service",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(dnanexus_service_info{delivery=\"containerized\", sre_role!~\"TIP.*\", service=\"$Service\"}) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Service",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(dnanexus_service_info{delivery=\"containerized\", sre_role!~\"TIP.*\", service=\"$Service\"}) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Service",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(dnanexus_service_info{delivery=\"containerized\", sre_role!~\"TIP.*\", service=\"$Service\"}) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Service",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(dnanexus_service_info{delivery=\"containerized\", sre_role!~\"TIP.*\", service=\"$Service\"}) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Service",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(dnanexus_service_info{delivery=\"containerized\", sre_role!~\"TIP.*\", service=\"$Service\"}) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Service",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(dnanexus_service_info{delivery=\"containerized\", sre_role!~\"TIP.*\", service=\"$Service\"}) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Service",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(dnanexus_service_info{delivery=\"containerized\", sre_role!~\"TIP.*\", service=\"$Service\"}) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Service",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(dnanexus_service_info{delivery=\"containerized\", sre_role!~\"TIP.*\", service=\"$Service\"}) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Service",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(dnanexus_service_info{delivery=\"containerized\", sre_role!~\"TIP.*\", service=\"$Service\"}) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Service",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(dnanexus_service_info{delivery=\"containerized\", sre_role!~\"TIP.*\", service=\"$Service\"}) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Service",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(dnanexus_service_info{delivery=\"containerized\", sre_role!~\"TIP.*\", service=\"$Service\"}) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Service",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(dnanexus_service_info{delivery=\"containerized\", sre_role!~\"TIP.*\", service=\"$Service\"}) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Service",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(dnanexus_service_info{delivery=\"containerized\", sre_role!~\"TIP.*\", service=\"$Service\"}) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Service",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(dnanexus_service_info{delivery=\"containerized\", sre_role!~\"TIP.*\", service=\"$Service\"}) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Service",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(dnanexus_service_info{delivery=\"containerized\", sre_role!~\"TIP.*\", service=\"$Service\"}) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "$Service",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(dnanexus_service_info{delivery=\"containerized\", sre_role!~\"TIP.*\", service=\"$Service\"}) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Uptime per Image",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime: $Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
     "repeat": "Image",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")",
       "legendFormat": "$Image ({{instance}})"
      }
     ]
    },
    {
     "title": "Uptime: $Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")",
       "legendFormat": "$Image ({{instance}})"
      }
     ]
    },
    {
     "title": "Uptime: $Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")",
       "legendFormat": "$Image ({{instance}})"
      }
     ]
    },
    {
     "title": "Uptime: $Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")",
       "legendFormat": "$Image ({{instance}})"
      }
     ]
    },
    {
     "title": "Uptime: $Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")",
       "legendFormat": "$Image ({{instance}})"
      }
     ]
    },
    {
     "title": "Uptime: $Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")",
       "legendFormat": "$Image ({{instance}})"
      }
     ]
    },
    {
     "title": "Uptime: $Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")",
       "legendFormat": "$Image ({{instance}})"
      }
     ]
    },
    {
     "title": "Uptime: $Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")",
       "legendFormat": "$Image ({{instance}})"
      }
     ]
    },
    {
     "title": "Uptime: $Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")",
       "legendFormat": "$Image ({{instance}})"
      }
     ]
    },
    {
     "title": "Uptime: $Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")",
       "legendFormat": "$Image ({{instance}})"
      }
     ]
    },
    {
     "title": "Uptime: $Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")",
       "legendFormat": "$Image ({{instance}})"
      }
     ]
    },
    {
     "title": "Uptime: $Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")",
       "legendFormat": "$Image ({{instance}})"
      }
     ]
    },
    {
     "title": "Uptime: $Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")",
       "legendFormat": "$Image ({{instance}})"
      }
     ]
    },
    {
     "title": "Uptime: $Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")",
       "legendFormat": "$Image ({{instance}})"
      }
     ]
    },
    {
     "title": "Uptime: $Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")",
       "legendFormat": "$Image ({{instance}})"
      }
     ]
    },
    {
     "title": "Uptime: $Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")",
       "legendFormat": "$Image ({{instance}})"
      }
     ]
    },
    {
     "title": "Uptime: $Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")",
       "legendFormat": "$Image ({{instance}})"
      }
     ]
    },
    {
     "title": "Uptime: $Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")",
       "legendFormat": "$Image ({{instance}})"
      }
     ]
    },
    {
     "title": "Uptime: $Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")",
       "legendFormat": "$Image ({{instance}})"
      }
     ]
    },
    {
     "title": "Uptime: $Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")",
       "legendFormat": "$Image ({{instance}})"
      }
     ]
    },
    {
     "title": "Uptime: $Image",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - label_replace(container_start_time_seconds{image=~\".*/$Image:.*\"}, \"version\", \"$1\", \"image\", \".*/.*:(.*)@.*\")",
       "legendFormat": "$Image ({{instance}})"
      }
     ]
    }
   ]
  }
 ]
}