{
 "title": "Lobby 4",
 "tags": [ "team-compute" ],
 "time": { "from": "now-6M", "to": "now" },
 "refresh": "1h",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<p style=\"text-align: center;font-size:50px\">Daily Totals: Past 6 Months</p>"
  },
  {
   "title": "Max Busy Workers Per Day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Max Busy Workers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "workers_by_state",
     "query": "SELECT max(\"numActive\") FROM \"longterm\".\"workers_by_state\" WHERE (\"state\" = 'busy') AND $timeFilter GROUP BY time($__interval, -16h), \"state\" fill(null)",
     "select": [
      [
       { "params": [ "numActive" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "busy" }
     ]
    }
   ]
  },
  {
   "title": "Compute Hours Per Day",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Compute Hours",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  (sum(\"timeDelta\") / 3600000) FROM \"jobStateTransitions\" WHERE ((\"from\" = 'running' AND \"to\" = 'done') OR (\"from\" = 'running' AND \"to\" = 'waiting_on_output')) AND $timeFilter GROUP BY time($__interval, -16h) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Completed Jobs Per Day",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Completed Jobs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "completed_jobs_by_region",
     "query": "SELECT sum(\"numCompleted\") FROM \"longterm\".\"completed_jobs_by_region\" WHERE $timeFilter GROUP BY time($__interval, -16h) fill(null)",
     "select": [
      [
       { "params": [ "numCompleted" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}