{
 "title": "Drone Cluster Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "agent",
    "label": "Agent",
    "query": "label_values(node_boot_time, instance)"
   },
   { "name": "port", "query": "9100" },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(node_boot_time, instance)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "DBInstance",
    "query": "label_values(aws_rds_select_latency_average,dbinstance_identifier)"
   }
  ]
 },
 "panels": [
  {
   "title": "Busy Agents",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "drone_running_jobs" }
   ]
  },
  {
   "title": "Queued Jobs",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "drone_pending_jobs" }
   ]
  },
  {
   "title": "Job Concurrency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "drone_running_jobs", "legendFormat": "Running Jobs" },
    { "expr": "drone_pending_jobs", "legendFormat": "Queued Jobs" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "content": "<p style=\"text-align: center;font-size:20px\">Drone Server</p>"
  },
  {
   "title": "CPU ($server)",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu{mode=\"system\",instance=~\"$server\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu{mode='user',instance=~\"$server\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu{mode='iowait',instance=~\"$server\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu{mode=~\".*irq\",instance=~\"$server\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$server\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu{mode='idle',instance=~\"$server\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory ($server)",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$server\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal{instance=~\"$server\"} - node_memory_MemFree{instance=~\"$server\"} - (node_memory_Cached{instance=~\"$server\"} + node_memory_Buffers{instance=~\"$server\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached{instance=~\"$server\"} + node_memory_Buffers{instance=~\"$server\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree{instance=~\"$server\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal{instance=~\"$server\"} - node_memory_SwapFree{instance=~\"$server\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "content": "<p style=\"text-align: center;font-size:20px\">Drone Agents</p>"
  },
  {
   "title": "CPU ($agent)",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 20 },
   "repeat": "agent",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu{mode=\"system\",instance=~\"$agent\"}[$interval])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu{mode='user',instance=~\"$agent\"}[$interval])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu{mode='iowait',instance=~\"$agent\"}[$interval])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu{mode=~\".*irq\",instance=~\"$agent\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$agent\"}[$interval])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu{mode='idle',instance=~\"$agent\"}[$interval])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory ($agent)",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 27 },
   "repeat": "agent",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$agent\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal{instance=~\"$agent\"} - node_memory_MemFree{instance=~\"$agent\"} - (node_memory_Cached{instance=~\"$agent\"} + node_memory_Buffers{instance=~\"$agent\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached{instance=~\"$agent\"} + node_memory_Buffers{instance=~\"$agent\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree{instance=~\"$agent\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal{instance=~\"$agent\"} - node_memory_SwapFree{instance=~\"$agent\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Disk ($agent)",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 34 },
   "repeat": "agent",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail{instance=~\"$agent\",device!~'rootfs'} * 100) / node_filesystem_size{instance=~\"$agent\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "TxRx ($agent)",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 41 },
   "repeat": "agent",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes{instance=~\"$agent\"}[5m])",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes{instance=~\"$agent\"}[5m])",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 48 },
   "content": "<p style=\"text-align: center;font-size:20px\">Drone RDS Database</p>"
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "aws_rds_cpuutilization_average", "legendFormat": "{{dbinstance_identifier}}" }
   ]
  },
  {
   "title": "Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aws_rds_queries_average", "legendFormat": "{{dbinstance_identifier}}" }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "aws_rds_network_transmit_throughput_average",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "Select Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "aws_rds_select_latency_average", "legendFormat": "{{dbinstance_identifier}}" }
   ]
  },
  {
   "title": "Insert Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "aws_rds_insert_latency_average", "legendFormat": "{{dbinstance_identifier}}" }
   ]
  },
  {
   "title": "Storage Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "aws_rds_volume_bytes_used_average",
     "legendFormat": "{{db_cluster_identifier}}"
    }
   ]
  },
  {
   "title": "Job Queue 95%ile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(drone3_queue_duration_histogram_bucket[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(drone3_queue_duration_histogram_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(drone3_queue_duration_histogram_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Job Queue 95%ile 12h",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 65 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(drone3_queue_duration_histogram_bucket[12h])) by (le))"
    }
   ]
  },
  {
   "title": "Job Queue 95%ile 12h",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 65 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(drone3_queue_duration_histogram_bucket[12h])) by (le))"
    }
   ]
  },
  {
   "title": "Job Queue 99%ile 1h",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 65 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(drone3_queue_duration_histogram_bucket[1h])) by (le))"
    }
   ]
  },
  {
   "title": "Job Duration 95%ile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(drone3_build_duration_histogram_bucket[5m])) by (le, repo))",
     "legendFormat": "p95 ({{repo}})"
    }
   ]
  },
  {
   "title": "Job Queue 95%ile 12h",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(drone3_queue_duration_histogram_bucket[12h])) by (le))"
    }
   ]
  },
  {
   "title": "Canary Job Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(drone_job_count{repo=\"sre-canary\",status=\"success\"}[5m])",
     "legendFormat": "Canary Success"
    },
    {
     "expr": "increase(drone_job_count{repo=\"sre-canary\",status=\"failure\"}[5m])",
     "legendFormat": "Canary Failure"
    }
   ]
  }
 ]
}