{
 "title": "TIP Metastore DB",
 "tags": [ "tip" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "db",
    "label": "DB Instance",
    "query": "label_values(aws_rds_select_latency_average, dbinstance_identifier)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(aws_rds_volume_bytes_used_average,db_cluster_identifier)"
   }
  ]
 },
 "panels": [
  {
   "title": "Select Latency ($db)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "repeat": "db",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "aws_rds_select_latency_average{dbinstance_identifier=~\"${db:pipe}\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "aws_rds_select_latency_p95{dbinstance_identifier=~\"${db:pipe}\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "aws_rds_select_latency_maximum{dbinstance_identifier=~\"${db:pipe}\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_average{dbinstance_identifier=~\"${db:pipe}\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "Insert Latency ($db)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "repeat": "db",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "aws_rds_insert_latency_average{dbinstance_identifier=~\"${db:pipe}\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "aws_rds_insert_latency_p95{dbinstance_identifier=~\"${db:pipe}\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "aws_rds_insert_latency_maximum{dbinstance_identifier=~\"${db:pipe}\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Network Tx per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "aws_rds_network_transmit_throughput_average{dbinstance_identifier=~\"${db:pipe}\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "Queries per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_rds_queries_average{dbinstance_identifier=~\"${db:pipe}\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "Storage Used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "aws_rds_volume_bytes_used_average{db_cluster_identifier=~\"${cluster:pipe}\"}",
     "legendFormat": "{{db_cluster_identifier}}"
    }
   ]
  },
  {
   "title": "Network Rx per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "aws_rds_network_receive_throughput_average{dbinstance_identifier=~\"${db:pipe}\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  }
 ]
}