{
 "title": "TIP Application Metrics",
 "tags": [ "tip" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Sessions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(thrift_session_count)" }
   ]
  },
  {
   "title": "Total Online Session",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(thrift_online_session_count)"
    }
   ]
  },
  {
   "title": "Total Running",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(thrift_total_running)" }
   ]
  },
  {
   "title": "Thrift Response Percentiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(dnax_thrift_exec_time_seconds_bucket{job=\"thrift\"}[10m])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(dnax_thrift_exec_time_seconds_bucket{job=\"thrift\"}[10m])) by (le))",
     "legendFormat": "75th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(dnax_thrift_exec_time_seconds_bucket{job=\"thrift\"}[10m])) by (le))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "SLA (10sec request count rate over 5m) - Appdex",
   "type": "graph",
   "description": "Upper limit of 10 seconds. Express the relative amount of requests served within 10sec and alert if the value drops below 0.75. Calculated over the last 5 minutes.\n\nAppdex score",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dnax_thrift_exec_time_seconds_bucket{le=\"10.0\"}[2m])) / sum(rate(dnax_thrift_exec_time_seconds_count[2m]))",
     "legendFormat": "75% <10sec over 5m"
    },
    {
     "expr": "(\n  sum(rate(dnax_thrift_exec_time_seconds_bucket{le=\"2.0\"}[2m])) +\n  sum(rate(dnax_thrift_exec_time_seconds_bucket{le=\"60.0\"}[2m])) \n) / 2 / sum(rate(dnax_thrift_exec_time_seconds_count[2m]))",
     "legendFormat": "Appdex score (2-60sec)"
    }
   ]
  },
  {
   "title": "Thrift execution time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum( increase ( dnax_thrift_exec_time_seconds_bucket[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total Thrift Queries",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(thrift_query_count)" }
   ]
  },
  {
   "title": "Total Metastore Requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(get_all_databases)" }
   ]
  },
  {
   "title": "Total API Server requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dnax_thrift_exec_time_seconds_count)"
    }
   ]
  },
  {
   "title": "Query Cancelled",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "thrift_query_terminated_count" }
   ]
  },
  {
   "title": "New Database",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(create_database)" }
   ]
  },
  {
   "title": "Create Table",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(create_directory)" }
   ]
  },
  {
   "title": "Pending Jobs (running but not started)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"pending_jobs\"})"
    }
   ]
  },
  {
   "title": "Active Tasks for Running Jobs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"num_active_tasks_running_jobs\"})"
    }
   ]
  },
  {
   "title": "Stage Run Distribution",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(stage_run_distribution_bucket[10m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Cancelled Query By Thrift Server",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(thrift_query_terminated_count[1m])*45",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Stage CPU Distribution",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(increase(stage_cpu_distribution_bucket[10m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Pending Jobs Distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_custom_gauge{custom=\"pending_jobs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Spark Jobs Running",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_custom_gauge{custom=\"jobs_running\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Executors - API Server Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "get_status_list_time_millis_mean",
     "legendFormat": "{{instance}} - get_status_list"
    },
    {
     "expr": "get_file_status_time_millis_mean",
     "legendFormat": "{{instance}} - get_file_status"
    },
    {
     "expr": "bytes_read_time_milliseconds_value_mean",
     "legendFormat": "{{instance}} - bytes read time"
    },
    {
     "expr": "bytes_written_time_milliseconds_value_mean",
     "legendFormat": "{{instance}} - bytes write time"
    },
    { "expr": "delete_file_time_millis_mean" },
    { "expr": "rename_file_time_millis_mean" }
   ]
  },
  {
   "title": "Thrift / Metastore - API Server Call Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(get_file_status{job=\"metastore\"}[5m]))",
     "legendFormat": "metastore get_file_status"
    },
    {
     "expr": "sum(rate(get_status_list{job=\"thrift\"}[5m]))",
     "legendFormat": "thrift get_status_list "
    },
    {
     "expr": "sum(rate(create_directory[5m]))",
     "legendFormat": "create_directory"
    },
    {
     "expr": "sum(rate(create_database{job=\"metastore\"}[5m]))",
     "legendFormat": "metastore create_database"
    },
    {
     "expr": "sum(rate(delete_file{job=\"metastore\"}[5m]))",
     "legendFormat": "metastore delete_file"
    },
    {
     "expr": "sum(rate(drop_database{job=\"metastore\"}[5m]))",
     "legendFormat": "metastore drop_database"
    },
    {
     "expr": "sum(rate(get_database_by_pattern{job=\"metastore\"}[5m]))",
     "legendFormat": "metastore get_database_by_pattern"
    },
    {
     "expr": "sum(rate(get_database{job=\"metastore\"}[5m]))",
     "legendFormat": "metastore get_database"
    },
    {
     "expr": "sum(rate(get_project{job=\"metastore\"}[5m]))",
     "legendFormat": "metastore get_project"
    }
   ]
  },
  {
   "title": "Bytes Read / Write",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(bytes_read_value_sum[10m])",
     "legendFormat": "{{instance}} bytes read "
    },
    {
     "expr": "rate(bytes_written_value_sum[10m])",
     "legendFormat": "{{instance}} bytes write"
    }
   ]
  },
  {
   "title": "Total Input Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "decbytes", "label": "Total Input Bytes" }
   ],
   "targets": [
    {
     "expr": "spark_custom_gauge{job=\"thrift\", custom=\"total_input_bytes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 55 },
   "content": "#### Spark job metrics history are capped at 1000 per thriftserver"
  },
  {
   "title": "Total Executor Count (non-driver)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 57 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"executor_count\"})"
    }
   ]
  },
  {
   "title": "Total On-Heap Executor Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 57 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"total_on_heap_memory\"})"
    }
   ]
  },
  {
   "title": "Total Executor Cores",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 57 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{job=\"thrift\", custom=\"total_cores\"})"
    }
   ]
  },
  {
   "title": "Total Executor Input Bytes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 57 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"total_input_bytes\"})"
    }
   ]
  },
  {
   "title": "Total SQL Queries",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 62 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{job=\"thrift\", custom=\"unique_job_group\"})"
    }
   ]
  },
  {
   "title": "Total Successful Job Group",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 62 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"succeeded_job_group\"})"
    }
   ]
  },
  {
   "title": "Total Active Stages",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 62 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"num_active_stages\"})"
    }
   ]
  },
  {
   "title": "Total Active Tasks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 62 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"num_active_tasks\"})"
    }
   ]
  },
  {
   "title": "Total Shuffle Writes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "decbytes", "label": "Total Input Bytes" }
   ],
   "targets": [
    {
     "expr": "spark_custom_gauge{job=\"thrift\", custom=\"total_shuffle_writes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Jobs Unknown",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 67 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"jobs_unknown\"})"
    }
   ]
  },
  {
   "title": "Total Failed Stages",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 67 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"num_failed_stages\"})"
    }
   ]
  },
  {
   "title": "Long Running Stages (>20sec)",
   "type": "singlestat",
   "description": "> 20sec",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 67 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{job=\"thrift\", custom=\"long_stages\"})"
    }
   ]
  },
  {
   "title": ">= 2 Stages per Job",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 67 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{job=\"thrift\", custom=\"many_stages\"})"
    }
   ]
  },
  {
   "title": "Total Skipped Stages",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 72 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"num_skipped_stages\"})"
    }
   ]
  },
  {
   "title": "Total Skipped Tasks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 72 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"num_skipped_tasks\"})"
    }
   ]
  },
  {
   "title": "Total Failed Tasks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 72 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"num_failed_tasks\"})"
    }
   ]
  },
  {
   "title": "Total Failed Job Group",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 72 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"jobs_failed\"})"
    }
   ]
  },
  {
   "title": "Total GC Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "ms", "label": "Total Input Bytes" }
   ],
   "targets": [
    {
     "expr": "spark_custom_gauge{job=\"thrift\", custom=\"total_gc_time\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Duration Spent (Executors)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 77 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"total_duration\"})"
    }
   ]
  },
  {
   "title": "Total Shuffle Reads",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 77 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"total_shuffle_reads\"})/(1024*1024)"
    }
   ]
  },
  {
   "title": "Total Shuffle Writes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 77 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"total_shuffle_writes\"})/(1024*1024)"
    }
   ]
  },
  {
   "title": "Number Completed Stages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_custom_gauge{job=\"thrift\", custom=\"num_completed_stages\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Stage Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "spark_custom_gauge{custom=\"avg_stage_time\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Input Records",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "none", "label": "Total Input Records" }
   ],
   "targets": [
    {
     "expr": "spark_custom_gauge{job=\"thrift\", custom=\"total_input_records\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Shuffle Reads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "decbytes", "label": "Total Input Bytes" }
   ],
   "targets": [
    {
     "expr": "spark_custom_gauge{job=\"thrift\", custom=\"total_shuffle_reads\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Bytes Spilled",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "decbytes", "label": "Total Input Bytes" }
   ],
   "targets": [
    {
     "expr": "spark_custom_gauge{job=\"thrift\", custom=\"total_memory_bytes_spilled\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}