{
 "title": "Docker Cron Cleanup",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Last Successful Run Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(docker_system_prune_last_reclaimed_space_bytes{exit_code=\"0\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last Failure Run Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(docker_system_prune_last_reclaimed_space_bytes{exit_code=\"1\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time Since Last Run",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "time() - node_textfile_mtime{file=\"docker_reclaimed_space.prom\"}"
    }
   ]
  },
  {
   "title": "Reclaimed Disk Space",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "docker_system_prune_last_reclaimed_space_bytes{exit_code=\"0\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time Since Last Run",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - node_textfile_mtime{file=\"docker_reclaimed_space.prom\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}