{
 "title": "Kernel Info",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Kernel Versions by Host",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "node_uname_info" }
   ]
  },
  {
   "title": "Kernel Versions by Major Version",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(node_uname_info{release=~\"5\\\\..*\"})",
     "legendFormat": "5.x.x"
    },
    {
     "expr": "count(node_uname_info{release=~\"4\\\\..*\"})",
     "legendFormat": "4.x.x"
    }
   ]
  },
  {
   "title": "Kernel Versions Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(node_uname_info) by (release)",
     "legendFormat": "{{release}}"
    }
   ]
  }
 ]
}