{
 "title": "TIP Performance",
 "tags": [ "tip" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Executors and Cores",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{job=\"thrift\", custom=\"total_cores\"})",
     "legendFormat": "Total Cores"
    },
    {
     "expr": "sum(spark_custom_gauge{custom=\"executor_count\"})",
     "legendFormat": "Executors"
    }
   ]
  },
  {
   "title": "Spark Skipped Tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(floor(rate(spark_custom_gauge{custom=\"num_skipped_tasks\"}[1m])))",
     "legendFormat": "Skipped Tasks"
    }
   ]
  },
  {
   "title": "Spark Jobs Running",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_custom_gauge{custom=\"jobs_running\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Queries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{job=\"thrift\", custom=\"unique_job_group\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Thrift User Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dnax_api{job=\"thrift\", operations=\"whoami\"}[20m])*3600",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Shuffle Writes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spark_custom_gauge{custom=\"total_shuffle_writes\"}[5m])/(1024*1024)",
     "legendFormat": "shuffle writes (GB)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 26 },
   "content": "#### Spark job metrics history are capped at 1000 per thriftserver"
  },
  {
   "title": "Total Shuffle Reads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spark_custom_gauge{custom=\"total_shuffle_reads\"}[5m])/(1024*1024)"
    }
   ]
  },
  {
   "title": "Used On-Heap Executor Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 28 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"used_on_heap_memory\"})/(1024*1024)"
    }
   ]
  },
  {
   "title": "Total On-Heap Executor Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 28 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"total_on_heap_memory\"})/(1024*1024)"
    }
   ]
  },
  {
   "title": "Total Executor Cores",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{job=\"thrift\", custom=\"total_cores\"})"
    }
   ]
  },
  {
   "title": "Total Executor Input Bytes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 28 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"total_input_bytes\"})/(1024*1024)"
    }
   ]
  },
  {
   "title": "Total Executor Count (non-driver)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"executor_count\"})"
    }
   ]
  },
  {
   "title": "Total Successful Job Group",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"succeeded_job_group\"})"
    }
   ]
  },
  {
   "title": "Total Active Stages",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"num_active_stages\"})"
    }
   ]
  },
  {
   "title": "Total Active Tasks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"num_active_tasks\"})"
    }
   ]
  },
  {
   "title": "Spark Active Stages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_custom_gauge{custom=\"num_active_stages\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total SQL Queries",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{job=\"thrift\", custom=\"unique_job_group\"})"
    }
   ]
  },
  {
   "title": "Total Failed Stages",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"num_failed_stages\"})"
    }
   ]
  },
  {
   "title": "Long Running Stages (>20sec)",
   "type": "singlestat",
   "description": "> 20sec",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{job=\"thrift\", custom=\"long_stages\"})"
    }
   ]
  },
  {
   "title": ">= 2 Stages per Job",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{job=\"thrift\", custom=\"many_stages\"})"
    }
   ]
  },
  {
   "title": "Total Jobs Unknown",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"jobs_unknown\"})"
    }
   ]
  },
  {
   "title": "Total Skipped Tasks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"num_skipped_tasks\"})"
    }
   ]
  },
  {
   "title": "Total Failed Tasks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"num_failed_tasks\"})"
    }
   ]
  },
  {
   "title": "Total Failed Job Group",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"jobs_failed\"})"
    }
   ]
  },
  {
   "title": "Spark Tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(spark_custom_gauge{custom=\"num_failed_tasks\"}[1m]))*100",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(rate(spark_custom_gauge{custom=\"num_active_tasks\"}[1m]))*100",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Total Skipped Stages",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 48 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"num_skipped_stages\"})"
    }
   ]
  },
  {
   "title": "Total Duration Spent (Executors)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 48 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"total_duration\"})"
    }
   ]
  },
  {
   "title": "Total Shuffle Reads",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 48 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"total_shuffle_reads\"})/(1024*1024)"
    }
   ]
  },
  {
   "title": "Total Shuffle Writes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 48 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_custom_gauge{custom=\"total_shuffle_writes\"})/(1024*1024)"
    }
   ]
  },
  {
   "title": "Number Completed Stages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spark_custom_gauge{job=\"thrift\", custom=\"num_completed_stages\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Thrift Server - API Server Calls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dnax_api{job=\"thrift\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Stage Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "spark_custom_gauge{custom=\"avg_stage_time\"}/10000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hive Metastore - API Server Calls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dnax_api{job=\"metastore\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API Server Call distribution",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum(increase(dnax_api[5m])) by (le)"
    }
   ]
  }
 ]
}