{
 "title": "Job Dashboard",
 "tags": [
  "sync",
  "team-compute"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Running Jobs By Region",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "region" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "running_jobs_by_region",
     "query": "SELECT count(DISTINCT(\"instanceId\")) FROM \"worker\" WHERE $timeFilter GROUP BY time($__interval), \"state\" fill(0)",
     "select": [
      [
       { "params": [ "numRunning" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Runnable Jobs By Region",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "region" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "runnable_jobs_by_region",
     "query": "SELECT count(DISTINCT(\"instanceId\")) FROM \"worker\" WHERE $timeFilter GROUP BY time($__interval), \"state\" fill(0)",
     "select": [
      [
       { "params": [ "numRunning" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job Runtime US-East-1",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "$tag__region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  \"timeDelta\" FROM \"jobStateTransitions\" WHERE ((\"from\" = 'running' AND \"to\" = 'done') OR (\"from\" = 'running' AND \"to\" = 'waiting_on_output')) AND \"region\"='aws:us-east-1' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job Runtime CN-North-1",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "alias": "$tag__region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  \"timeDelta\" FROM \"jobStateTransitions\" WHERE ((\"from\" = 'running' AND \"to\" = 'done') OR (\"from\" = 'running' AND \"to\" = 'waiting_on_output')) AND \"region\"='aws:cn-north-1' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job Runtime AP-SouthEast-2",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 7 },
   "targets": [
    {
     "alias": "$tag__region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  \"timeDelta\" FROM \"jobStateTransitions\" WHERE ((\"from\" = 'running' AND \"to\" = 'done') OR (\"from\" = 'running' AND \"to\" = 'waiting_on_output')) AND \"region\"='aws:ap-southeast-2' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job Runtime EU-Central-1",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 7 },
   "targets": [
    {
     "alias": "$tag__region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  \"timeDelta\" FROM \"jobStateTransitions\" WHERE ((\"from\" = 'running' AND \"to\" = 'done') OR (\"from\" = 'running' AND \"to\" = 'waiting_on_output')) AND \"region\"='aws:eu-central-1' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job Runtime Azure WestUS",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 7 },
   "targets": [
    {
     "alias": "$tag__region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  \"timeDelta\" FROM \"jobStateTransitions\" WHERE ((\"from\" = 'running' AND \"to\" = 'done') OR (\"from\" = 'running' AND \"to\" = 'waiting_on_output')) AND \"region\"='azure:westus' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Completed Jobs Per Region",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "region" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "completed_jobs_by_region",
     "query": "SELECT max(\"numCompleted\") FROM \"longterm\".\"completed_jobs_by_region\" WHERE $timeFilter GROUP BY time($__interval), \"region\" fill(0)",
     "select": [
      [
       { "params": [ "numCompleted" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Jobs Per Region",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "region" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "failed_jobs_by_region",
     "query": "SELECT count(DISTINCT(\"jobId\")) FROM \"jobStateTransitions\" WHERE \"to\" = 'failed' AND $timeFilter GROUP BY time($__interval), \"region\" fill(0)",
     "select": [
      [
       { "params": [ "numFailed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Terminated Jobs Per Region",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "region" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "terminated_jobs_by_region",
     "query": "SELECT count(DISTINCT(\"jobId\")) FROM \"jobStateTransitions\" WHERE \"to\" = 'terminated' AND $timeFilter GROUP BY time($__interval), \"region\" fill(0)",
     "select": [
      [
       { "params": [ "numTerminated" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AWS US-East Spot To OnDemand",
   "type": "graph",
   "description": "The number of jobs switched to onDemand from spot instances",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "# Jobs To OnDemand" }
   ],
   "targets": [
    {
     "alias": "$tag_instanceType",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(DISTINCT(\"jobID\")) FROM \"spotToOnDemand\" WHERE $timeFilter AND \"region\"='aws:us-east-1' GROUP BY instanceType, time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AWS Spot Preemptions",
   "type": "graph",
   "description": "Spot jobs preempted by spot market conditions",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "# Jobs To OnDemand" }
   ],
   "targets": [
    {
     "alias": "$tag_instanceType",
     "expr": "increase(spot_preemptions_total[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{region}}:{{instance_type}}",
     "query": "SELECT COUNT(DISTINCT(\"instanceId\")) FROM \"terminatedSirs\" WHERE $timeFilter AND \"region\"='us-east-1' GROUP BY instanceType, time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Non-Spot Job Assignable Duration",
   "type": "graph",
   "description": "The length of time a job waits after becoming \nassignable to getting a worker",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_region",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "jobLogs",
     "query": "SELECT \"duration\" FROM \"assignableDuration\" WHERE $timeFilter AND \"instanceType\" !~ /_s_/ AND \"isWRD\" = 'false' GROUP BY region",
     "select": [
      [
       { "params": [ "numLines" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "[[tag_region]]_WRD",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "jobLogs",
     "query": "SELECT \"duration\" FROM \"assignableDuration\" WHERE $timeFilter AND \"instanceType\" !~ /_s_/ AND \"isWRD\" = 'true' GROUP BY region",
     "select": [
      [
       { "params": [ "numLines" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Spot Job Assignable Duration",
   "type": "graph",
   "description": "The length of time a job waits after becoming \nassignable to getting a worker",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_region",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "jobLogs",
     "query": "SELECT \"duration\" FROM \"assignableDuration\" WHERE $timeFilter AND \"instanceType\" =~ /_s_/ AND \"isWRD\" = 'false' GROUP BY region",
     "select": [
      [
       { "params": [ "numLines" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "[[tag_region]]_WRD",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "jobLogs",
     "query": "SELECT \"duration\" FROM \"assignableDuration\" WHERE $timeFilter AND \"instanceType\" =~ /_s_/ AND \"isWRD\" = 'true' GROUP BY region",
     "select": [
      [
       { "params": [ "numLines" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "US-East Spot Job Assignable Duration By InstType",
   "type": "graph",
   "description": "The length of time a non-WRD spot job waits after becoming assignable to getting a worker",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_instanceType",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "jobLogs",
     "query": "SELECT \"duration\" FROM \"assignableDuration\" WHERE $timeFilter AND \"instanceType\" =~ /_s_/ AND \"region\"='aws:us-east-1' AND \"isWRD\" = 'false' GROUP BY instanceType",
     "select": [
      [
       { "params": [ "numLines" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of restartable jobs",
   "type": "graph",
   "description": "If the restart job daemon is functioning, we expect this to be near 0.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MEAN(\"numRestartable\") FROM \"jobRestartDaemon\" WHERE $timeFilter GROUP BY time(15m) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Jobs by OS Release",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_osRelease",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "osRelease" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "active_jobs_by_os_release",
     "select": [
      [
       { "params": [ "numActiveJobs" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Idle Jobs",
   "type": "graph",
   "description": "Jobs should transition from idle to runnable quickly.  Sustained periods with many idle jobs could indicate an issue processing new job events.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activeJobs",
     "query": "SELECT COUNT(DISTINCT(\"jobId\")) FROM \"activeJobs\" WHERE (\"state\" = 'idle') AND $timeFilter GROUP BY time(2m), region fill(0)",
     "select": [
      [
       { "params": [ "jobid" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "idle" }
     ]
    }
   ]
  }
 ]
}