{
 "title": "Salesforced",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Heartbeats",
   "type": "graph",
   "description": "Every heartbeat corresponds to 1 salesforced event loop iteration",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "heartbeats/hour" }
   ],
   "targets": [
    {
     "expr": "increase(salesforced_heartbeats_total[1h])"
    }
   ]
  },
  {
   "title": "Health status",
   "type": "singlestat",
   "description": "The salesforced's health status. Green (1) if a heartbeat has been received in the last hour, red (0) otherwise",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "changes(salesforced_heartbeats_total[1h]) > bool 0"
    }
   ]
  },
  {
   "title": "Failed salesforced-to-salesforce connections",
   "type": "graph",
   "description": "Number of failed connections from salesforced to salesforce",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "connections/minute" }
   ],
   "targets": [
    {
     "expr": "increase(salesforced_bad_sf_conns_total[1h])"
    }
   ]
  },
  {
   "title": "Change requests by fulfillment status code",
   "type": "graph",
   "description": "The number of change requests processed by the salesforced, by fulfillment status code",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "requests/minute" }
   ],
   "targets": [
    {
     "expr": "sum(increase(salesforced_fulfillments_total[1h])) by (code)"
    }
   ]
  },
  {
   "title": "Fulfillments by action/resource",
   "type": "graph",
   "description": "The number of fulfilled change requests, by action/resource",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "fulfillments/minute" }
   ],
   "targets": [
    {
     "expr": "sum(increase(salesforced_fulfillments_total{code=\"200\"}[1h])) by (resource, action)"
    }
   ]
  }
 ]
}