{
 "title": "Pilot Versions",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(dnanexus_pilot_up, instance)"
   },
   {
    "name": "Compliant",
    "label": "Compliant Versions",
    "query": "1f217978222d6bd3d44ef7b997a6d53bc450676e"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h1>Pilot Version</center>"
  },
  {
   "title": "Compliant Pilot Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(dnanexus_pilot_up{version=~\"$Compliant\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Non-Compliant Pilot Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(dnanexus_pilot_up{version!~\"NOT_INSTALLED\", version!~\"$Compliant\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Pilot Not Installed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(dnanexus_pilot_up{version=~\"NOT_INSTALLED\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Compliant",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "dnanexus_pilot_up{version=~\"$Compliant\"}"
    }
   ]
  },
  {
   "title": "Non-Compliant",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "dnanexus_pilot_up{version!~\"NOT_INSTALLED\",version!~\"$Compliant\"}"
    }
   ]
  },
  {
   "title": "Pilot Not Installed",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "dnanexus_pilot_up{version=~\"NOT_INSTALLED\"}"
    }
   ]
  },
  {
   "title": "Compliant vs. Non-Compliant Over Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Num of Instances" }
   ],
   "targets": [
    {
     "expr": "sum(dnanexus_pilot_up{version=~\"$Compliant\"})",
     "legendFormat": "Compliant"
    },
    {
     "expr": "sum(dnanexus_pilot_up{version!~\"$Compliant\",version!~\"NOT_INSTALLED\"})",
     "legendFormat": "Non-Compliant"
    }
   ]
  },
  {
   "title": "Pilot Upness Over Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Num of Instances" }
   ],
   "targets": [
    { "expr": "count(dnanexus_pilot_up==1)", "legendFormat": "Up" },
    { "expr": "count(dnanexus_pilot_up==0)", "legendFormat": "Down" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
   "content": "<center><h1>Pilot Service Status</center>"
  },
  {
   "title": "Pilot Service Up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(dnanexus_pilot_up==1) or vector(0)"
    }
   ]
  },
  {
   "title": "Pilot Service Down",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(dnanexus_pilot_up==0) or vector(0)"
    }
   ]
  },
  {
   "title": "Pilot Service Up",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 34 },
   "targets": [
    { "expr": "dnanexus_pilot_up==1" }
   ]
  },
  {
   "title": "Pilot Service Down",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 34 },
   "targets": [
    { "expr": "dnanexus_pilot_up==0" }
   ]
  }
 ]
}