{
 "title": "GitHub Actions Usage",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "repo",
    "query": {
     "query": "label_values(github_actions_workflow_minutes_used_total, repo)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "This Month's Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_actions_total_minutes_used / github_actions_included_minutes"
    }
   ]
  },
  {
   "title": "Usage Over Time vs. Monthly Included Minutes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "github_actions_total_minutes_used",
     "legendFormat": "Used Minutes"
    },
    {
     "expr": "github_actions_total_paid_minutes_used",
     "legendFormat": "Paid Minutes"
    }
   ]
  },
  {
   "title": "This Month's Cost",
   "type": "stat",
   "description": "$0.008 per minute over 50k",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_actions_total_paid_minutes_used * 0.008"
    }
   ]
  },
  {
   "title": "Monthly Billable Charges",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "github_actions_total_paid_minutes_used * 0.008",
     "legendFormat": "Paid Minutes"
    }
   ]
  },
  {
   "title": "Minutes Used in Current Billing Cycle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total) by (repo)",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Minutes Used Per Day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(github_actions_workflow_minutes_used_total[1d])) by (repo)",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Minutes Used Per Hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(github_actions_workflow_minutes_used_total[1h])) by (repo)",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  { "title": "Workflow Usage per Repo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 47 },
   "repeat": "repo",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 65 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 65 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 74 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 74 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 83 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 83 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 92 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 92 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 101 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_actions_workflow_minutes_used_total{repo=\"$repo\"}) by (workflowName)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "API Requests Per Hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(github_actions_api_request_count[1h])",
     "legendFormat": "Requests per Hour"
    }
   ]
  }
 ]
}