{
 "title": "Kinesis Audit Log Stream",
 "tags": [
  "audit-log",
  "data-team"
 ],
 "time": { "from": "2018-07-18T16:24:13.775Z", "to": "2018-07-18T22:24:19.173Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Incoming Records",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Total Incoming Records" }
   ],
   "targets": [
    {
     "expr": "aws_kinesis_incoming_records_sum{stream_name=\"dx-auditlog-stream-vprod\"}",
     "legendFormat": "Total Incoming Records"
    }
   ]
  },
  {
   "title": "Incoming Data (MB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Total Incoming Data (MB)" }
   ],
   "targets": [
    {
     "expr": "(aws_kinesis_incoming_bytes_sum{stream_name=\"dx-auditlog-stream-vprod\"})/1000000",
     "legendFormat": "Total Incoming Data (MB)"
    }
   ]
  },
  {
   "title": "Write Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Write Latency (ms)" }
   ],
   "targets": [
    {
     "expr": "aws_kinesis_put_records_latency_average{stream_name=\"dx-auditlog-stream-vprod\"}",
     "legendFormat": "Average Write Latency (ms)"
    },
    {
     "expr": "aws_kinesis_put_records_latency_maximum{stream_name=\"dx-auditlog-stream-vprod\"}",
     "legendFormat": "Maximum Write Latency (ms)"
    }
   ]
  },
  {
   "title": "Read Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Read Latency (ms)" }
   ],
   "targets": [
    {
     "expr": "aws_kinesis_get_records_latency_average{stream_name=\"dx-auditlog-stream-vprod\"}",
     "legendFormat": "Average Read Latency (ms)"
    },
    {
     "expr": "aws_kinesis_get_records_latency_maximum{stream_name=\"dx-auditlog-stream-vprod\"}",
     "legendFormat": "Maximum Read Latency (ms)"
    }
   ]
  },
  {
   "title": "Average Consumer Lag (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms", "label": "Iterator Lag (ms)" }
   ],
   "targets": [
    {
     "expr": "aws_kinesis_get_records_iterator_age_milliseconds_average{stream_name=\"dx-auditlog-stream-vprod\"}",
     "legendFormat": "Average Iterator Age (ms)"
    },
    {
     "expr": "aws_kinesis_get_records_iterator_age_milliseconds_maximum{stream_name=\"dx-auditlog-stream-vprod\"}",
     "legendFormat": "Maximum Iterator Age (ms)"
    }
   ]
  },
  {
   "title": "Throttled Reads & Writes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Throttled Requests" }
   ],
   "targets": [
    {
     "expr": "aws_kinesis_read_provisioned_throughput_exceeded_sum{stream_name=\"dx-auditlog-stream-vprod\"}",
     "legendFormat": "Total Throttled Read Throughput"
    },
    {
     "expr": "aws_kinesis_write_provisioned_throughput_exceeded_sum{stream_name=\"dx-auditlog-stream-vprod\"}",
     "legendFormat": "Total Throttled Write Throughput"
    }
   ]
  }
 ]
}