{
 "title": "Container Cleanup",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Destroyable Containers Backlog",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "data_destroyable_containers" }
   ]
  },
  {
   "title": "Destroyable Containers Backlog",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 0 },
   "targets": [
    { "expr": "data_destroyable_containers", "legendFormat": "data_destroyable_containers" }
   ]
  },
  {
   "title": "Processed Containers within 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum (increase(containers_deleted[5m]))"
    }
   ]
  },
  {
   "title": "Containers Cleaned from Backlog in the Last Day",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "-1 * delta(data_destroyable_containers[1d])",
     "legendFormat": "data_destroyable_containers"
    }
   ]
  },
  {
   "title": "Containers Cleaned Up from Backlog within 10 minutes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "-1 * delta(data_destroyable_containers[10m])",
     "legendFormat": "data_destroyable_containers"
    }
   ]
  },
  {
   "title": "Processed Hardlinks within 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum (increase(hardlinks_deleted[5m]))"
    }
   ]
  },
  {
   "title": "Approx. Hours to Empty Backlog",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "data_destroyable_containers / clamp_min(-1 * delta(data_destroyable_containers[1h]), 0)",
     "legendFormat": "data_destroyable_containers"
    }
   ]
  },
  {
   "title": "% of Containers Cleaned within 30 Minutes since deletedAt during Last Day",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cleanup_from_deleted_at_duration_seconds_bucket{le=\"1800\"}[1d])) / sum(rate(container_cleanup_from_deleted_at_duration_seconds_count[1d]))"
    }
   ]
  },
  {
   "title": "% of Containers Cleaned within 30 Minutes since deletedAt",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cleanup_from_deleted_at_duration_seconds_bucket{le=\"1800\"}[1h])) / sum(rate(container_cleanup_from_deleted_at_duration_seconds_count[1h]))"
    }
   ]
  },
  {
   "title": "Duration to Cleanup Container since deletedAt",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(container_cleanup_from_deleted_at_duration_seconds_bucket[10m])))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le) (rate(container_cleanup_from_deleted_at_duration_seconds_bucket[10m])))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(container_cleanup_from_deleted_at_duration_seconds_bucket[10m])))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "% of Containers Cleaned within 30 Minutes since destroyAt during Last Day",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cleanup_from_destroy_at_duration_seconds_bucket{le=\"1800\"}[1d])) / sum(rate(container_cleanup_from_destroy_at_duration_seconds_count[1d]))"
    }
   ]
  },
  {
   "title": "% of Containers Cleaned within 30 Minutes since destroyAt",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 16 },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cleanup_from_destroy_at_duration_seconds_bucket{le=\"1800\"}[1h])) / sum(rate(container_cleanup_from_destroy_at_duration_seconds_count[1h]))"
    }
   ]
  },
  {
   "title": "Duration to Cleanup Container since destroyAt",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(container_cleanup_from_destroy_at_duration_seconds_bucket[10m])))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le) (rate(container_cleanup_from_destroy_at_duration_seconds_bucket[10m])))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(container_cleanup_from_destroy_at_duration_seconds_bucket[10m])))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Cron Lambda Avg. Duration (ms)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time (aws_lambda_duration_average{function_name=~\"containercleanup-cron-.*\"}[1h])"
    }
   ]
  },
  {
   "title": "Cron Lambda Duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 22 },
   "targets": [
    {
     "expr": "avg (aws_lambda_duration_average{function_name=~\"containercleanup-cron-.*\"})",
     "legendFormat": "{{function_name}}"
    }
   ]
  },
  {
   "title": "Consumer Message Duration in seconds",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (job, le) (rate(consumer_message_duration_seconds_bucket{instance=~\"containercleanup.*\"}[10m])))",
     "legendFormat": "{{job}}-0.9"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (job, le) (rate(consumer_message_duration_seconds_bucket{instance=~\"containercleanup.*\"}[10m])))",
     "legendFormat": "{{job}}-0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (job, le) (rate(consumer_message_duration_seconds_bucket{instance=~\"containercleanup.*\"}[10m])))",
     "legendFormat": "{{job}}-0.5"
    }
   ]
  },
  {
   "title": "Cron Lambda Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum (aws_lambda_errors_sum{function_name=~\"containercleanup-cron-.*\"})",
     "legendFormat": "{{function_name}}"
    }
   ]
  },
  {
   "title": "Duration to Process 1 Hardlink in Container Deleter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (job, le) (rate(container_deleter_per_hardlink_duration_seconds_bucket[10m])))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (job, le) (rate(container_deleter_per_hardlink_duration_seconds_bucket[10m])))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (job, le) (rate(container_deleter_per_hardlink_duration_seconds_bucket[10m])))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Duration to Process 1 Hardlink in Hardlink Deleter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (job, le) (rate(hardlinks_deleter_per_hardlink_duration_seconds_bucket[10m])))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (job, le) (rate(hardlinks_deleter_per_hardlink_duration_seconds_bucket[10m])))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (job, le) (rate(hardlinks_deleter_per_hardlink_duration_seconds_bucket[10m])))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Consumer Processing Errors by Job in the Last 24 hours",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (round(delta(consumer_processing_error{instance=~\"containercleanup.*\"}[24h])))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Consumer Processing Errors by Job",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 32 },
   "targets": [
    {
     "expr": "sum by (job) (delta(consumer_processing_error{instance=~\"containercleanup.*\"}[30s]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Duration to Process 1 Data Object in Orphan Deleter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (job, le) (rate(orphan_deleter_per_data_object_duration_seconds_bucket[10m])))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (job, le) (rate(orphan_deleter_per_data_object_duration_seconds_bucket[10m])))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (job, le) (rate(orphan_deleter_per_data_object_duration_seconds_bucket[10m])))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Messages Received/Deleted by Queue",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 38 },
   "targets": [
    {
     "expr": "aws_sqs_number_of_messages_received_sum{queue_name=~\"Delete(Container|Hardlink)Queue-.*\"}",
     "legendFormat": "{{queue_name}} (received)"
    },
    {
     "expr": "aws_sqs_number_of_messages_deleted_sum{queue_name=~\"Delete(Container|Hardlink)Queue-.*\"}",
     "legendFormat": "{{queue_name}} (deleted)"
    }
   ]
  },
  {
   "title": "Consumer Errors by Job in the Last 24 hours",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (round(delta(consumer_error{instance=~\"containercleanup.*\"}[24h])))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Consumer Errors by Job",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 38 },
   "targets": [
    {
     "expr": "sum by (job) (delta(consumer_error{instance=~\"containercleanup.*\"}[30s]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DeleteContainerQueue visible messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_visible_sum{queue_name=~\"DeleteContainerQueue-.*\"}"
    }
   ]
  },
  {
   "title": "DeleteContainerQueue visible messages",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 44 },
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_visible_sum{queue_name=~\"DeleteContainerQueue-.*\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "DeleteContainerQueue not_visible messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_not_visible_sum{queue_name=~\"DeleteContainerQueue-.*\"}"
    }
   ]
  },
  {
   "title": "DeleteContainerQueue not_visible messages",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 44 },
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_not_visible_sum{queue_name=~\"DeleteContainerQueue-.*\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "DeleteHardlinkQueue visible messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_visible_sum{queue_name=~\"DeleteHardlinkQueue-.*\"}"
    }
   ]
  },
  {
   "title": "DeleteHardlinkQueue visible messages",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 49 },
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_visible_sum{queue_name=~\"DeleteHardlinkQueue-.*\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "DeleteHardlinkQueue not_visible messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_not_visible_sum{queue_name=~\"DeleteHardlinkQueue-.*\"}"
    }
   ]
  },
  {
   "title": "DeleteHardlinkQueue not_visible messages",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 49 },
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_not_visible_sum{queue_name=~\"DeleteHardlinkQueue-.*\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Dead Letter Queue messages",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_visible_sum{queue_name=~\"Delete(Container|Hardlink)QueueDLQ-.*\"} + aws_sqs_approximate_number_of_messages_not_visible_sum{queue_name=~\"Delete(Container|Hardlink)QueueDLQ-.*\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Dead Letter Queue messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 54 },
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_visible_sum{queue_name=~\"Delete(Container|Hardlink)QueueDLQ-.*\"} + aws_sqs_approximate_number_of_messages_not_visible_sum{queue_name=~\"Delete(Container|Hardlink)QueueDLQ-.*\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Age of Oldest Message by Queue",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_sqs_approximate_age_of_oldest_message_maximum{queue_name=~\"Delete(Container|Hardlink)Queue(?:DLQ)?-.*\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Age of Oldest Message by Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 54 },
   "targets": [
    {
     "expr": "aws_sqs_approximate_age_of_oldest_message_maximum{queue_name=~\"Delete(Container|Hardlink)Queue(?:DLQ)?-.*\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  }
 ]
}