{
 "title": "Process Monitoring",
 "description": "Process metrics exported by https://github.com/ncabatoff/process-exporter.",
 "tags": [ "devops" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" },
   {
    "name": "host",
    "query": "label_values(namedprocess_scrape_errors, instance)"
   },
   {
    "name": "processes",
    "query": "label_values(namedprocess_namegroup_cpu_seconds_total{instance=~\"${host:pipe}\"},groupname)"
   }
  ]
 },
 "panels": [
  {
   "title": "num processes ($processes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "repeat": "processes",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_num_procs{groupname=~\"$processes\",instance=~\"$host\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "num processes ($processes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_num_procs{groupname=~\"$processes\",instance=~\"$host\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "num processes ($processes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_num_procs{groupname=~\"$processes\",instance=~\"$host\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "cpu ($processes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "repeat": "processes",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval])) / sum(rate(node_cpu{job=\"node\", instance=~\"$host\"}[$interval]))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "cpu ($processes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval])) / sum(rate(node_cpu{job=\"node\", instance=~\"$host\"}[$interval]))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "cpu ($processes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval])) / sum(rate(node_cpu{job=\"node\", instance=~\"$host\"}[$interval]))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "resident memory ($processes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "repeat": "processes",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=~\"$processes\",instance=~\"$host\", memtype=\"resident\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "resident memory ($processes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=~\"$processes\",instance=~\"$host\", memtype=\"resident\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "resident memory ($processes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=~\"$processes\",instance=~\"$host\", memtype=\"resident\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "virtual memory ($processes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "repeat": "processes",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=~\"$processes\",instance=~\"$host\", memtype=\"virtual\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "virtual memory ($processes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=~\"$processes\",instance=~\"$host\", memtype=\"virtual\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "virtual memory ($processes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=~\"$processes\",instance=~\"$host\", memtype=\"virtual\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "read bytes ($processes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "repeat": "processes",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "read bytes ($processes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "read bytes ($processes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "write bytes ($processes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "repeat": "processes",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "write bytes ($processes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "write bytes ($processes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  }
 ]
}