{
 "title": "Docker Versions",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(cadvisor_version_info, instance)"
   },
   { "name": "Compliant", "query": "19.03.12" }
  ]
 },
 "panels": [
  {
   "title": "Compliant Instances",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(cadvisor_version_info{dockerVersion=~\"$Compliant\"})"
    }
   ]
  },
  {
   "title": "Non-Compliant Instances",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 11, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(cadvisor_version_info{dockerVersion!~\"$Compliant\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Compliant",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "cadvisor_version_info{dockerVersion=~\"$Compliant\"}"
    }
   ]
  },
  {
   "title": "Non-Compliant",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 12, "x": 11, "y": 4 },
   "targets": [
    {
     "expr": "cadvisor_version_info{dockerVersion!~\"$Compliant\"}"
    }
   ]
  },
  {
   "title": "Compliant vs. Non-Compliant Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Num of Instances" }
   ],
   "targets": [
    {
     "expr": "sum(cadvisor_version_info{dockerVersion=~\"$Compliant\"})",
     "legendFormat": "Compliant"
    },
    {
     "expr": "sum(cadvisor_version_info{dockerVersion!~\"$Compliant\"})",
     "legendFormat": "Non-Compliant"
    }
   ]
  }
 ]
}