{
 "title": "Node Exporter Versions",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_exporter_build_info, version)"
    }
   },
   { "name": "Compliant", "label": "Compliant Versions", "query": "1.1.2" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1>Pilot Version</center>"
   }
  },
  {
   "title": "Compliant Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_exporter_build_info{version=~\"$Compliant\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Non-Compliant Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_exporter_build_info{version!~\"$Compliant\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Compliant vs. Non-Compliant Over Time",
   "type": "graph",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Num of Instances" }
   ],
   "targets": [
    {
     "expr": "sum(node_exporter_build_info{version=~\"$Compliant\"})",
     "legendFormat": "Compliant"
    },
    {
     "expr": "sum(node_exporter_build_info{version!~\"$Compliant\",version!~\"NOT_INSTALLED\"})",
     "legendFormat": "Non-Compliant"
    }
   ]
  },
  {
   "title": "Compliant",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "node_exporter_build_info{version=~\"$Compliant\"}"
    }
   ]
  },
  {
   "title": "Non-Compliant",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "node_exporter_build_info{version!~\"$Compliant\"}"
    }
   ]
  }
 ]
}