{
 "title": "VPN Status",
 "tags": [ "devops" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "spokes",
    "query": {
     "query": "label_values(probe_success{job=\"vpn_ping_hub_us_east_1\"},spoke)"
    }
   },
   {
    "name": "spokes_to_hub",
    "query": {
     "query": "label_values(probe_success{hub=\"AWS US East 1\"},spoke)"
    }
   },
   {
    "name": "vpn_node",
    "label": "Network Traffic Host:",
    "query": "label_values(node_boot_time, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes{device=\"tun0\"}[5m])",
     "legendFormat": "recv {{instance}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes{device=\"tun0\"}[5m])",
     "legendFormat": "trans {{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "options": {
    "content": "<h1 style=\"color: #5e9ca0; text-align: center;\">&nbsp;</h1>\n\n<h1 style=\"color: #5e9ca0; text-align: center;\"><span style=\"color: #ffffff;\">Hub to Spoke Communications</span></h1>\n"
   }
  },
  {
   "title": "Hub to Spoke Ping Times (s)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"vpn_ping_hub_us_east_1\"} < 5",
     "legendFormat": "{{spoke}}"
    }
   ]
  },
  {
   "title": "Packet Loss 👿",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(probe_success{job=\"vpn_ping_hub_us_east_1\"} == 0) by (spoke)",
     "legendFormat": "{{spoke}}"
    }
   ]
  },
  {
   "title": "Hub to $spokes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 31 },
   "repeat": "spokes",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{job=\"vpn_ping_hub_us_east_1\", spoke=\"$spokes\"}"
    }
   ]
  },
  {
   "title": "Hub to $spokes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{job=\"vpn_ping_hub_us_east_1\", spoke=\"$spokes\"}"
    }
   ]
  },
  {
   "title": "Hub to $spokes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{job=\"vpn_ping_hub_us_east_1\", spoke=\"$spokes\"}"
    }
   ]
  },
  {
   "title": "Hub to $spokes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{job=\"vpn_ping_hub_us_east_1\", spoke=\"$spokes\"}"
    }
   ]
  },
  {
   "title": "Hub to $spokes Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 34 },
   "repeat": "spokes",
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(probe_success{job=\"vpn_ping_hub_us_east_1\", spoke=\"$spokes\"}[$__range])"
    }
   ]
  },
  {
   "title": "Hub to $spokes Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 34 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(probe_success{job=\"vpn_ping_hub_us_east_1\", spoke=\"$spokes\"}[$__range])"
    }
   ]
  },
  {
   "title": "Hub to $spokes Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 34 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(probe_success{job=\"vpn_ping_hub_us_east_1\", spoke=\"$spokes\"}[$__range])"
    }
   ]
  },
  {
   "title": "Hub to $spokes Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 34 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(probe_success{job=\"vpn_ping_hub_us_east_1\", spoke=\"$spokes\"}[$__range])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 37 },
   "options": {
    "content": "<h1 style=\"color: #5e9ca0; text-align: center;\">&nbsp;</h1>\n\n<h1 style=\"color: #5e9ca0; text-align: center;\"><span style=\"color: #ffffff;\">Spoke to Hub Communications</span></h1>\n"
   }
  },
  {
   "title": "Spoke to Hub Ping Times (s)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{hub=\"AWS US East 1\"} < 5",
     "legendFormat": "{{spoke}}"
    }
   ]
  },
  {
   "title": "Packet Loss 👿",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(probe_success{hub=\"AWS US East 1\"} == 0) by (spoke)"
    }
   ]
  },
  {
   "title": "Spoke $spokes_to_hub to Hub",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 61 },
   "repeat": "spokes_to_hub",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{hub=\"AWS US East 1\", spoke=\"$spokes_to_hub\"}",
     "legendFormat": "{{spoke}}"
    }
   ]
  },
  {
   "title": "Spoke $spokes_to_hub to Hub",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 61 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{hub=\"AWS US East 1\", spoke=\"$spokes_to_hub\"}",
     "legendFormat": "{{spoke}}"
    }
   ]
  },
  {
   "title": "Spoke $spokes_to_hub to Hub",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 61 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{hub=\"AWS US East 1\", spoke=\"$spokes_to_hub\"}",
     "legendFormat": "{{spoke}}"
    }
   ]
  },
  {
   "title": "Spoke $spokes_to_hub to Hub",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 61 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{hub=\"AWS US East 1\", spoke=\"$spokes_to_hub\"}",
     "legendFormat": "{{spoke}}"
    }
   ]
  },
  {
   "title": "Spoke $spokes_to_hub to Hub Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 64 },
   "repeat": "spokes_to_hub",
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(probe_success{hub=\"AWS US East 1\", spoke=\"$spokes_to_hub\"}[$__range])"
    }
   ]
  },
  {
   "title": "Spoke $spokes_to_hub to Hub Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 64 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(probe_success{hub=\"AWS US East 1\", spoke=\"$spokes_to_hub\"}[$__range])"
    }
   ]
  },
  {
   "title": "Spoke $spokes_to_hub to Hub Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 64 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(probe_success{hub=\"AWS US East 1\", spoke=\"$spokes_to_hub\"}[$__range])"
    }
   ]
  },
  {
   "title": "Spoke $spokes_to_hub to Hub Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 64 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(probe_success{hub=\"AWS US East 1\", spoke=\"$spokes_to_hub\"}[$__range])"
    }
   ]
  }
 ]
}