{
 "title": "Audit Log - DynamoDB",
 "description": "Dashboard for the Audit Log table in DynamoDB",
 "tags": [
  "audit-log",
  "data-team"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "dx-auditlog-vprod - Write Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Write Capacity Units" }
   ],
   "targets": [
    {
     "expr": "aws_dynamodb_consumed_write_capacity_units_sum{table_name=\"dx-auditlog-vprod\"}",
     "legendFormat": "Consumed Write Capacity Units"
    }
   ]
  },
  {
   "title": "dx-auditlog-vprod - Read Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Read Capacity Units" }
   ],
   "targets": [
    {
     "expr": "aws_dynamodb_consumed_read_capacity_units_sum{table_name=\"dx-auditlog-vprod\"}",
     "legendFormat": "Consumed Read Capacity Units"
    },
    {
     "expr": "aws_dynamodb_provisioned_read_capacity_units_sum{table_name=\"dx-auditlog-vprod\"}",
     "legendFormat": "Provisioned Read Capacity Units"
    }
   ]
  },
  {
   "title": "dx-auditlog-vprod - Request Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Average Latency (ms)" }
   ],
   "targets": [
    {
     "expr": "aws_dynamodb_successful_request_latency_average{operation=\"BatchWriteItem\",table_name=\"dx-auditlog-vprod\"}",
     "legendFormat": "Average Write Latency (ms)"
    },
    {
     "expr": "aws_dynamodb_successful_request_latency_average{operation=\"Query\", table_name=\"dx-auditlog-vprod\"}",
     "legendFormat": "Average Read Latency (ms)"
    }
   ]
  },
  {
   "title": "dx-auditlog-vprod - Throttled Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Throttled Requests" }
   ],
   "targets": [
    {
     "expr": "aws_dynamodb_throttled_requests_sum{table_name=\"dx-auditlog-vprod\"}",
     "legendFormat": "Throttled Requests"
    }
   ]
  },
  {
   "title": "OrgIdAuditLogIndex - Write Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Write Capacity Units" }
   ],
   "targets": [
    {
     "expr": "aws_dynamodb_consumed_write_capacity_units_index_sum{table_name=\"dx-auditlog-vprod\", global_secondary_index_name=\"OrgIdAuditLogIndex\"}",
     "legendFormat": "Consumed Write Capacity Units"
    },
    {
     "expr": "aws_dynamodb_provisioned_write_capacity_units_index_sum{table_name=\"dx-auditlog-vprod\", global_secondary_index_name=\"OrgIdAuditLogIndex\"}",
     "legendFormat": "Provisioned Write Capacity Units"
    }
   ]
  },
  {
   "title": "OrgIdAuditLogIndex - Read Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Read Capacity Units" }
   ],
   "targets": [
    {
     "expr": "aws_dynamodb_consumed_read_capacity_units_index_sum{table_name=\"dx-auditlog-vprod\", global_secondary_index_name=\"OrgIdAuditLogIndex\"}",
     "legendFormat": "Consumed Read Capacity"
    },
    {
     "expr": "aws_dynamodb_provisioned_read_capacity_units_index_sum{table_name=\"dx-auditlog-vprod\", global_secondary_index_name=\"OrgIdAuditLogIndex\"}",
     "legendFormat": "Provisioned Read Capacity"
    }
   ]
  },
  {
   "title": "OrgIdAuditLogIndex - Throttled Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Throttled Requests" }
   ],
   "targets": [
    {
     "expr": "aws_dynamodb_write_throttle_events_index_sum{table_name=\"dx-auditlog-vprod\", global_secondary_index_name=\"OrgIdAuditLogIndex\"}",
     "legendFormat": "Write Throttled Events"
    },
    {
     "expr": "aws_dynamodb_read_throttle_events_index_sum{table_name=\"dx-auditlog-vprod\", global_secondary_index_name=\"OrgIdAuditLogIndex\"}",
     "legendFormat": "Read Throttled Events"
    }
   ]
  },
  {
   "title": "ShardIdSeqNumAuditLogIndex - Throttled Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Throttled Requests" }
   ],
   "targets": [
    {
     "expr": "aws_dynamodb_write_throttle_events_index_sum{table_name=\"dx-auditlog-vprod\", global_secondary_index_name=\"ShardIdSeqNumAuditLogIndex\"}",
     "legendFormat": "Write Throttled Events"
    },
    {
     "expr": "aws_dynamodb_read_throttle_events_index_sum{table_name=\"dx-auditlog-vprod\", global_secondary_index_name=\"ShardIdSeqNumAuditLogIndex\"}",
     "legendFormat": "Read Throttled Events"
    }
   ]
  },
  {
   "title": "ShardIdSeqNumAuditLogIndex - Write Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Write Capacity Units" }
   ],
   "targets": [
    {
     "expr": "aws_dynamodb_consumed_write_capacity_units_index_sum{table_name=\"dx-auditlog-vprod\", global_secondary_index_name=\"ShardIdSeqNumAuditLogIndex\"}",
     "legendFormat": "Consumed Write Capacity Units"
    },
    {
     "expr": "aws_dynamodb_provisioned_write_capacity_units_index_sum{table_name=\"dx-auditlog-vprod\", global_secondary_index_name=\"ShardIdSeqNumAuditLogIndex\"}",
     "legendFormat": "Provisioned Write Capacity Units"
    }
   ]
  },
  {
   "title": "ShardIdSeqNumAuditLogIndex - Read Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Read Capacity Units" }
   ],
   "targets": [
    {
     "expr": "aws_dynamodb_consumed_read_capacity_units_index_sum{table_name=\"dx-auditlog-vprod\", global_secondary_index_name=\"ShardIdSeqNumAuditLogIndex\"}",
     "legendFormat": "Consumed Read Capacity"
    },
    {
     "expr": "aws_dynamodb_provisioned_read_capacity_units_index_sum{table_name=\"dx-auditlog-vprod\", global_secondary_index_name=\"ShardIdSeqNumAuditLogIndex\"}",
     "legendFormat": "Provisioned Read Capacity"
    }
   ]
  }
 ]
}