{
 "title": "Apollo Vizserver",
 "tags": [ "tip" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Vizserver Restart",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "vizserver_restart_counter_created{job=\"vizserver\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Redis Network Bytes Traffic In/Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "aws_elasticache_network_bytes_in_average",
     "legendFormat": "bytes in {{cache_cluster_id}}"
    },
    {
     "expr": "aws_elasticache_network_bytes_out_average",
     "legendFormat": "bytes out {{cache_cluster_id}}"
    }
   ]
  },
  {
   "title": "Vizserver Restart Timeline",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vizserver_restart_counter_created{job=\"vizserver\"}[1m]) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Redis Cache Used - Byte Actual",
   "type": "graph",
   "description": "Actual Bytes used in AWS Elasticache Redis. Alerts if usage is greater than 90% of env. E.g. vdev 1.55GB, staging and prod 3.0GB.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "Rate Bytes change" }
   ],
   "targets": [
    {
     "expr": "aws_elasticache_bytes_used_for_cache_average{job=\"cloudwatch\"}",
     "legendFormat": "{{cache_cluster_id}}"
    }
   ]
  },
  {
   "title": "Redis Current Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elasticache_curr_connections_average",
     "legendFormat": "connections {{cache_cluster_id}}"
    }
   ]
  },
  {
   "title": "Redis Cache Misses to Hits ratio",
   "type": "graph",
   "description": "Alerts if ratio of misses to hits is greater than 0.4",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elasticache_cache_misses_average{job=\"cloudwatch\"}/aws_elasticache_cache_hits_average{job=\"cloudwatch\"}",
     "legendFormat": "{{cache_cluster_id}}"
    }
   ]
  },
  {
   "title": "Redis Cache Hits/Misses/Evictions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elasticache_cache_hits_average",
     "legendFormat": "hits {{cache_cluster_id}}"
    },
    {
     "expr": "aws_elasticache_cache_misses_average",
     "legendFormat": "misses {{cache_cluster_id}}"
    },
    {
     "expr": "aws_elasticache_evictions_average",
     "legendFormat": "evictions {{cache_cluster_id}}"
    }
   ]
  },
  {
   "title": "Redis Freeable Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "aws_elasticache_freeable_memory_average",
     "legendFormat": "{{cache_cluster_id}}"
    }
   ]
  },
  {
   "title": "Redis CPU and Engine Utilization % ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Utilization %" }
   ],
   "targets": [
    {
     "expr": "aws_elasticache_cpuutilization_average",
     "legendFormat": "cpu utilization {{cache_cluster_id}}"
    },
    {
     "expr": "aws_elasticache_engine_cpuutilization_average",
     "legendFormat": "engine utilization {{cache_cluster_id}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 32 },
   "content": "\n#### Query Stats - Request Statistics"
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 34 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "query_stats_total{job=\"vizserver\"}",
     "legendFormat": "success {{instance}}"
    }
   ]
  },
  {
   "title": "Active",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 34 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "query_stats_active{job=\"vizserver\"}",
     "legendFormat": "success {{instance}}"
    }
   ]
  },
  {
   "title": "Cancelled",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 34 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "query_stats_cancelled{job=\"vizserver\"}",
     "legendFormat": "success {{instance}}"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 34 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "query_stats_timeout{job=\"vizserver\"}",
     "legendFormat": "success {{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 38 },
   "content": "\n#### 10 min Window - Request Statistics"
  },
  {
   "title": "Redis Cache Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 40 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "aws_elasticache_bytes_used_for_cache_average{cache_cluster_id=\"dnax-tip-viz-cache-1-001\"}"
    },
    {}
   ]
  },
  {
   "title": "Redis Current Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 40 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aws_elasticache_curr_connections_average)"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 40 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "window_stats_total{job=\"vizserver\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Success",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 40 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "window_stats_success{job=\"vizserver\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 40 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "window_stats_failed{job=\"vizserver\"}",
     "legendFormat": "success {{instance}}"
    }
   ]
  },
  {
   "title": "Cancelled",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 40 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "window_stats_cancelled{job=\"vizserver\"}",
     "legendFormat": "success {{instance}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 44 }, "content": "\n#### Uptimes" },
  {
   "title": "TIP and VIZ sync failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aws_sqs_tip_sync_dequeue_failure[1m])",
     "legendFormat": "tip sync failure"
    },
    {
     "expr": "rate(aws_sqs_viz_sync_dequeue_failure[1m])",
     "legendFormat": "viz sync failure"
    }
   ]
  },
  {
   "title": "Instance Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 46 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "system_boot_time{job=\"vizserver\"}"
    }
   ]
  },
  {
   "title": "Process Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 46 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_create_time{job=\"vizserver\"}"
    }
   ]
  },
  {
   "title": "CPU Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 46 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "system_cpu_count{job=\"vizserver\"}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 51 }, "content": "\n#### Key System Metrics" },
  {
   "title": "Query Statistics",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "query_stats_cancelled{job=\"vizserver\"}",
     "legendFormat": "cancelled {{instance}}"
    },
    {
     "expr": "query_stats_active{job=\"vizserver\"}",
     "legendFormat": "active {{instance}}"
    },
    {
     "expr": "query_stats_failed{job=\"vizserver\"}",
     "legendFormat": "failed {{instance}}"
    },
    {
     "expr": "query_stats_timeout{job=\"vizserver\"}",
     "legendFormat": "timeout {{instance}}"
    }
   ]
  },
  {
   "title": "System CPU %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "system_cpu_percent{job=\"vizserver\"}"
    }
   ]
  },
  {
   "title": "System Virtual Mem %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 53 },
   "targets": [
    {
     "expr": "system_virtual_memory_percent{job=\"vizserver\"}"
    }
   ]
  },
  {
   "title": "System Disk Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 53 },
   "targets": [
    {
     "expr": "system_disk_usage_percent{job=\"vizserver\"}"
    }
   ]
  },
  {
   "title": "Process CPU %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "process_cpu_percent{job=\"vizserver\"}"
    }
   ]
  },
  {
   "title": "System Swap Memory %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 57 },
   "targets": [
    {
     "expr": "system_swap_memory_percent{job=\"vizserver\"}"
    }
   ]
  },
  {
   "title": "Sys Info Process CPU %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 57 },
   "targets": [
    {
     "expr": "sys_info_process_cpu_percent{job=\"vizserver\"}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 61 }, "content": "\n#### Application LRU Cache" },
  {
   "title": "Max",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 63 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "cache_maxsize{job=\"vizserver\"}",
     "legendFormat": "maxsize {{instance}}"
    }
   ]
  },
  {
   "title": "Current",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 63 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "cache_currsize{job=\"vizserver\"}",
     "legendFormat": "currsize {{instance}}"
    }
   ]
  },
  {
   "title": "Hits",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 63 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "cache_hits{job=\"vizserver\"}",
     "legendFormat": "hits {{instance}}"
    }
   ]
  },
  {
   "title": "Misses",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 63 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "cache_hits{job=\"vizserver\"}",
     "legendFormat": "misses {{instance}}"
    }
   ]
  },
  {
   "title": "Count Cohort Response",
   "type": "graph",
   "description": "Percentile comparison for Count Cohort API",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(count_cohort_time_millis_bucket[10m])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(count_cohort_time_millis_bucket[10m])) by (le))",
     "legendFormat": "75th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(count_cohort_time_millis_bucket[10m])) by (le))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Count Cohort Response",
   "type": "graph",
   "description": "Percentile comparison for Count Cohort API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(count_cohort_time_millis_bucket[10m])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(count_cohort_time_millis_bucket[10m])) by (le))",
     "legendFormat": "75th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(count_cohort_time_millis_bucket[10m])) by (le))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Genomic Range Response",
   "type": "graph",
   "description": "Percentile comparison for Genomic Range API",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(genomic_range_time_millis_bucket[10m])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(genomic_range_time_millis_bucket[10m])) by (le))",
     "legendFormat": "75th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(genomic_range_time_millis_bucket[10m])) by (le))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Histogram Response",
   "type": "graph",
   "description": "Percentile comparison for Histogram API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(histogram_time_millis_bucket[10m])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(histogram_time_millis_bucket[10m])) by (le))",
     "legendFormat": "75th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(histogram_time_millis_bucket[10m])) by (le))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Dashboard Config Response",
   "type": "graph",
   "description": "Percentile comparison for Dashboard Config API",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(dashboard_config_time_millis_bucket[10m])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(dashboard_config_time_millis_bucket[10m])) by (le))",
     "legendFormat": "75th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(dashboard_config_time_millis_bucket[10m])) by (le))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Fields Json Response",
   "type": "graph",
   "description": "Percentile comparison for Fields Json API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(fields_json_time_millis_bucket[10m])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(fields_json_time_millis_bucket[10m])) by (le))",
     "legendFormat": "75th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(fields_json_time_millis_bucket[10m])) by (le))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Download Manifest Response",
   "type": "graph",
   "description": "Percentile comparison for Download Manifest API",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(download_manifest_time_millis_bucket[10m])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(download_manifest_time_millis_bucket[10m])) by (le))",
     "legendFormat": "75th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(download_manifest_time_millis_bucket[10m])) by (le))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Locus Details Response",
   "type": "graph",
   "description": "Percentile comparison for Locus Details API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(locus_details_time_millis_bucket[10m])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(locus_details_time_millis_bucket[10m])) by (le))",
     "legendFormat": "75th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(locus_details_time_millis_bucket[10m])) by (le))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "System Swap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(system_virtual_memory_active[10m]))",
     "legendFormat": "active"
    },
    {
     "expr": "sum(rate(system_virtual_memory_available[10m]))",
     "legendFormat": "available"
    },
    {
     "expr": "sum(rate(system_swap_memory_free[10m]))",
     "legendFormat": "free"
    },
    {
     "expr": "sum(rate(system_swap_memory_sin[10m]))",
     "legendFormat": "sin"
    },
    {
     "expr": "sum(rate(system_swap_memory_sout[10m]))",
     "legendFormat": "sout"
    },
    {
     "expr": "sum(rate(system_swap_memory_total[10m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(system_swap_memory_used[10m]))",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "System Virtual Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(system_virtual_memory_active[10m]))",
     "legendFormat": "active"
    },
    {
     "expr": "sum(rate(system_virtual_memory_available[10m]))",
     "legendFormat": "available"
    },
    {
     "expr": "sum(rate(system_virtual_memory_free[10m]))",
     "legendFormat": "free"
    },
    {
     "expr": "sum(rate(system_virtual_memory_cached[10m]))",
     "legendFormat": "cached"
    },
    {
     "expr": "sum(rate(system_virtual_memory_inactive[10m]))",
     "legendFormat": "inactive"
    },
    {
     "expr": "sum(rate(system_virtual_memory_shared[10m]))",
     "legendFormat": "shared"
    }
   ]
  }
 ]
}