{
 "title": "Headwaters Container Monitoring",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "server",
    "label": "Node",
    "query": "label_values(cadvisor_version_info, instance)"
   },
   {
    "name": "Service",
    "query": "label_values(container_memory_rss{instance=\"$server\"}, container_label_com_docker_stack_namespace)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h4>Host-Level Metrics</h4></center>"
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time{instance=~\"$server.*\"}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\",instance=~\"$server.*\"}[$interval]))"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$server.*\"}) /  count(count(node_cpu{instance=~\"$server.*\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Used RAM",
   "type": "singlestat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_MemTotal{instance=~\"$server.*\"} - node_memory_MemFree{instance=~\"$server.*\"}) / (node_memory_MemTotal{instance=~\"$server.*\"} )) * 100"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "min((node_filesystem_size{fstype=~\"xfs|ext4\",instance=~\"$server.*\"} - node_filesystem_free{fstype=~\"xfs|ext4\",instance=~\"$server.*\"} )/ node_filesystem_size{fstype=~\"xfs|ext4\",instance=~\"$server.*\"})"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_memory_SwapTotal{instance=~'$server.*'} - node_memory_SwapFree{instance=~'$server.*'})"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\",instance=~\"$server.*\"}[$interval])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\",instance=~\"$server.*\"}[$interval])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu{mode=\"system\",instance=~\"$server.*\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu{mode='user',instance=~\"$server.*\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu{mode='iowait',instance=~\"$server.*\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu{mode=~\".*irq\",instance=~\"$server.*\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$server.*\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu{mode='idle',instance=~\"$server.*\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server.*\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=~\"$server.*\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=~\"$server.*\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$server.*\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal{instance=~\"$server.*\"} - node_memory_MemFree{instance=~\"$server.*\"} - (node_memory_Cached{instance=~\"$server.*\"} + node_memory_Buffers{instance=~\"$server.*\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached{instance=~\"$server.*\"} + node_memory_Buffers{instance=~\"$server.*\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree{instance=~\"$server.*\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal{instance=~\"$server.*\"} - node_memory_SwapFree{instance=~\"$server.*\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail{instance=~\"$server.*\",device!~'rootfs'} * 100) / node_filesystem_size{instance=~\"$server.*\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(node_disk_bytes_read[$interval])) by (device)",
     "legendFormat": "OUT on /{{device}}"
    },
    {
     "expr": "sum(rate(node_disk_bytes_written[$interval])) by (device)",
     "legendFormat": "IN on /{{device}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
   "content": "<center><h4>Container-Level Metrics</h4></center>"
  },
  {
   "title": "Memory Usage Per Container Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name=~\".+\",instance=~\"$server.*\",container_label_com_docker_stack_namespace=~\"${Service:pipe}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage (Relative to Limit)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(((container_memory_working_set_bytes{name=~\".+\", instance=~\"$server.*\"}) / container_spec_memory_limit_bytes{instance=~\"$server.*\",container_label_com_docker_stack_namespace=~\"${Service:pipe}\"}) * 100)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Current Memory Usage Per Container",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{name!=\"\",instance=~\"$server\",container_label_com_docker_stack_namespace=~\"${Service:pipe}\"}) by (name) "
    },
    {
     "expr": "max(container_spec_memory_limit_bytes{name!=\"\",instance=~\"$server\",container_label_com_docker_stack_namespace=~\"${Service:pipe}\"} -container_memory_working_set_bytes{name!=\"\",instance=~\"$server\",container_label_com_docker_stack_namespace=~\"${Service:pipe}\"}) by (name) > 0"
    },
    {
     "expr": "max(container_spec_memory_limit_bytes{name!=\"\",instance=~\"$server\",container_label_com_docker_stack_namespace=~\"${Service:pipe}\"}) by (name) > 0 "
    },
    {
     "expr": "((max(container_memory_working_set_bytes{name!=\"\",instance=~\"$server\"}) by (name)) / (max(container_spec_memory_limit_bytes{name!=\"\",instance=~\"$server\",container_label_com_docker_stack_namespace=~\"${Service:pipe}\"}) by (name) > 0))"
    }
   ]
  },
  {
   "title": "Number of Container Restarts",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "changes(sum(container_start_time_seconds{container_label_com_docker_swarm_service_name=~\".+\",instance=~\"$server\",container_label_com_docker_stack_namespace=~\"${Service:pipe}\"}) by (container_label_com_docker_swarm_service_name)[10m:])"
    },
    {
     "expr": "changes(sum(container_start_time_seconds{container_label_com_docker_swarm_service_name=~\".+\",instance=~\"$server\",container_label_com_docker_stack_namespace=~\"${Service:pipe}\"}) by (container_label_com_docker_swarm_service_name)[1h:])"
    },
    {
     "expr": "changes(sum(container_start_time_seconds{container_label_com_docker_swarm_service_name=~\".+\",instance=~\"$server\",container_label_com_docker_stack_namespace=~\"${Service:pipe}\"}) by (container_label_com_docker_swarm_service_name)[24h:])"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\",instance=~\"$server.*\",container_label_com_docker_stack_namespace=~\"${Service:pipe}\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\",instance=~\"$server.*\",container_label_com_docker_stack_namespace=~\"${Service:pipe}\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\",instance=~\"$server.*\",container_label_com_docker_stack_namespace=~\"${Service:pipe}\"}[$interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Swap per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_swap{name=~\".+\",instance=~\"$server.*\",container_label_com_docker_stack_namespace=~\"${Service:pipe}\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}