{
 "title": "ElastiCache",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Freeable Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes", "label": "Freeable memory" }
   ],
   "targets": [
    {
     "expr": "aws_elasticache_freeable_memory_average",
     "legendFormat": "{{cache_cluster_id}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CPU %" }
   ],
   "targets": [
    {
     "expr": "aws_elasticache_cpuutilization_average",
     "legendFormat": "{{cache_cluster_id}}"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "aws_elasticache_curr_connections_average",
     "legendFormat": "{{cache_cluster_id}}"
    }
   ]
  },
  {
   "title": "Bytes used for cache",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes used for Cache" }
   ],
   "targets": [
    {
     "expr": "aws_elasticache_bytes_used_for_cache_average",
     "legendFormat": "{{cache_cluster_id}}"
    }
   ]
  },
  {
   "title": "Current Items",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elasticache_curr_items_average",
     "legendFormat": "{{cache_cluster_id}}"
    }
   ]
  },
  {
   "title": "Master Instance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "is master" }
   ],
   "targets": [
    {
     "expr": "aws_elasticache_is_master_average",
     "legendFormat": "{{cache_cluster_id}}"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Replication lag (s)" }
   ],
   "targets": [
    {
     "expr": "aws_elasticache_replication_lag_average",
     "legendFormat": "{{cache_cluster_id}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } }
 ]
}